[install]
minimumReleaseAge = 86400
minimumReleaseAgeExcludes = [
    "@types/node",
    "eslint",
    "tsx",
    "typescript"
]
linker = "hoisted"

[install.security]
scanner = "@socketsecurity/bun-security-scanner"
