[phases.setup]
nixPkgs = ['...', 'nodejs', 'bun']

[phases.install]
cmds = ['bun install']

[phases.build]
cmds = ['bun run build:inspector']

[variables]
NIXPACKS_NODE_VERSION = '24'
SKIP_INSTALL_SIMPLE_GIT_HOOKS = '1'
