[
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
      "**/*.astro",
      "**/*.vue",
    ],
    "name": "moso/eslint-comments",
    "plugins": [
      "@eslint-community/eslint-comments",
    ],
    "rules": [
      "@eslint-community/eslint-comments/disable-enable-pair",
      "@eslint-community/eslint-comments/no-aggregating-enable",
      "@eslint-community/eslint-comments/no-duplicate-disable",
      "@eslint-community/eslint-comments/no-unlimited-disable",
      "@eslint-community/eslint-comments/no-unused-enable",
    ],
  },
  {
    "ignores": [
      "**/node_modules",
      "**/dist",
      "**/lib",
      "**/package-lock.json",
      "**/yarn.lock",
      "**/pnpm-lock.yaml",
      "**/bun.lockb",
      "**/bun.lock",
      "**/output",
      "**/coverage",
      "**/temp",
      "**/.temp",
      "**/tmp",
      "**/.tmp",
      "**/.history",
      "**/.vitepress/cache",
      "**/.nuxt",
      "**/.next",
      "**/.vercel",
      "**/.changeset",
      "**/.idea",
      "**/.cache",
      "**/.output",
      "**/.vite-inspect",
      "**/.yarn",
      "**/vite.config.*.timestamp-*",
      "**/CHANGELOG*.md",
      "**/*.min.*",
      "**/LICENSE*",
      "**/__snapshots__",
      "**/auto-import?(s).ts",
      "**/auto-import?(s).d.ts",
      "**/components.ts",
      "**/components.d.ts",
      "**/typegen.ts",
      "**/typegen.d.ts",
    ],
    "name": "moso/ignores/globals",
  },
  {
    "ignores": [
      "**/node_modules/",
      "**/.cache/",
      "**/.env",
      "**/.DS_Store",
      "**/.vite-ssg-dist/",
      "**/.vite-ssg-temp/",
      "**/*.log",
      "**/dist/",
      "**/dist-ssr/",
      "public/assets/fonts",
      "**/temp/",
      "**/components.d.ts",
      "**/auto-imports.d.ts",
      "**/*.local",
      "**/.idea/",
      "**/typings/",
      "src/typegen.d.ts",
      "**/.astro/",
      "**/.content-collections",
      ".phpunit.cache",
      ".phpunit.result.cache",
      "storage/*.key",
      "storage/assets",
      "storage/dropfolder",
      "vendor",
      "**/Homestead.json",
      "**/Homestead.yaml",
      "**/auth.json",
      "**/.claude/",
      "**/.cursor/",
      ".github/hooks/",
      ".github/copilot-instuctions.md",
      ".vscode/CLAUDE.md",
      ".vscode/settings.json",
      ".vscode/mcp.json",
      ".mcp.json",
      "CLAUDE.md",
      "PROJECT.md",
      "**/.eslint-config-inspector/",
      "**/coverage/",
      "**/sponsors.*",
      "**/drafts/",
    ],
    "name": "moso/ignores/gitignore",
  },
  {
    "name": "moso/imports",
    "plugins": [
      "@moso",
      "import-lite",
    ],
    "rules": [
      "@moso/no-import-duplicates",
      "@moso/no-import-from-dist",
      "@moso/no-import-node-modules-by-path",
      "import-lite/consistent-type-specifier-style",
      "import-lite/first",
      "import-lite/no-duplicates",
      "import-lite/no-mutable-exports",
      "import-lite/no-named-default",
      "import-lite/newline-after-import",
    ],
  },
  {
    "files": [
      "**/?(.)*.d.?([cm])ts",
      "**/*.?([cm])ts",
      "**/*.?([cm])tsx",
    ],
    "name": "moso/imports/typescript",
    "rules": [
      "@typescript-eslint/no-import-type-side-effects",
      "@typescript-eslint/consistent-type-imports",
    ],
  },
  {
    "languageOptions": {
      "ecmaVersion": "latest",
      "parserOptions": {
        "ecmaFeatures": {
          "jsx": true,
        },
        "ecmaVersion": "latest",
        "sourceType": "module",
      },
      "sourceType": "module",
    },
    "linterOptions": {
      "reportUnusedDisableDirectives": true,
    },
    "name": "moso/javascript",
    "plugins": [
      "@eslint/js",
      "unused-imports",
    ],
    "rules": [
      "constructor-super",
      "for-direction",
      "getter-return",
      "no-async-promise-executor",
      "no-case-declarations",
      "no-class-assign",
      "no-compare-neg-zero",
      "no-cond-assign",
      "no-const-assign",
      "no-constant-binary-expression",
      "no-constant-condition",
      "no-control-regex",
      "no-debugger",
      "no-delete-var",
      "no-dupe-args",
      "no-dupe-class-members",
      "no-dupe-else-if",
      "no-dupe-keys",
      "no-duplicate-case",
      "no-empty",
      "no-empty-character-class",
      "no-empty-pattern",
      "no-empty-static-block",
      "no-ex-assign",
      "no-extra-boolean-cast",
      "no-fallthrough",
      "no-func-assign",
      "no-global-assign",
      "no-import-assign",
      "no-invalid-regexp",
      "no-irregular-whitespace",
      "no-loss-of-precision",
      "no-misleading-character-class",
      "no-new-native-nonconstructor",
      "no-nonoctal-decimal-escape",
      "no-obj-calls",
      "no-octal",
      "no-prototype-builtins",
      "no-redeclare",
      "no-regex-spaces",
      "no-self-assign",
      "no-setter-return",
      "no-shadow-restricted-names",
      "no-sparse-arrays",
      "no-this-before-super",
      "no-unassigned-vars",
      "no-undef",
      "no-unexpected-multiline",
      "no-unreachable",
      "no-unsafe-finally",
      "no-unsafe-negation",
      "no-unsafe-optional-chaining",
      "no-unused-labels",
      "no-unused-private-class-members",
      "no-unused-vars",
      "no-useless-assignment",
      "no-useless-backreference",
      "no-useless-catch",
      "no-useless-escape",
      "no-with",
      "preserve-caught-error",
      "require-yield",
      "use-isnan",
      "valid-typeof",
      "array-callback-return",
      "no-await-in-loop",
      "no-constructor-return",
      "no-duplicate-imports",
      "no-inner-declarations",
      "no-promise-executor-return",
      "no-self-compare",
      "no-template-curly-in-string",
      "no-unmodified-loop-condition",
      "no-unreachable-loop",
      "no-use-before-define",
      "require-atomic-updates",
      "accessor-pairs",
      "arrow-body-style",
      "block-scoped-var",
      "- camelcase",
      "class-methods-use-this",
      "consistent-return",
      "- consistent-this",
      "curly",
      "default-case-last",
      "dot-notation",
      "eqeqeq",
      "func-name-matching",
      "func-style",
      "grouped-accessor-pairs",
      "guard-for-in",
      "new-cap",
      "no-alert",
      "no-array-constructor",
      "no-caller",
      "no-console",
      "no-else-return",
      "no-eq-null",
      "no-eval",
      "no-extra-bind",
      "no-implied-eval",
      "no-invalid-this",
      "no-iterator",
      "no-label-var",
      "no-labels",
      "no-lone-blocks",
      "no-lonely-if",
      "no-loop-func",
      "no-multi-assign",
      "no-multi-str",
      "no-new",
      "no-new-func",
      "no-new-wrappers",
      "no-object-constructor",
      "no-octal-escape",
      "no-param-reassign",
      "no-proto",
      "no-restricted-globals",
      "no-restricted-properties",
      "no-restricted-syntax",
      "- no-return-assign",
      "no-sequences",
      "no-throw-literal",
      "no-undef-init",
      "no-unneeded-ternary",
      "no-unused-expressions",
      "no-useless-call",
      "no-useless-computed-key",
      "no-useless-concat",
      "no-useless-constructor",
      "no-useless-rename",
      "no-var",
      "object-shorthand",
      "one-var",
      "operator-assignment",
      "prefer-arrow-callback",
      "prefer-const",
      "prefer-destructuring",
      "prefer-exponentiation-operator",
      "prefer-numeric-literals",
      "prefer-object-has-own",
      "prefer-object-spread",
      "prefer-promise-reject-errors",
      "prefer-regex-literals",
      "prefer-rest-params",
      "prefer-spread",
      "prefer-template",
      "radix",
      "require-await",
      "require-unicode-regexp",
      "strict",
      "symbol-description",
      "vars-on-top",
      "yoda",
      "unicode-bom",
      "unused-imports/no-unused-imports",
      "unused-imports/no-unused-vars",
    ],
  },
  {
    "name": "moso/javascript/opinionated",
    "plugins": [
      "@moso",
      "de-morgan",
    ],
    "rules": [
      "@moso/avoid-barrel-files",
      "@moso/no-bidi",
      "@moso/no-invisible-characters",
      "@moso/no-redundant-variable",
      "@moso/no-string-interpolation",
      "@moso/no-top-level-await",
      "@moso/no-unneeded-array-flat-map",
      "@moso/prefer-early-return",
      "@moso/prefer-fetch",
      "@moso/prefer-reduce-over-chaining",
      "de-morgan/no-negated-conjunction",
      "de-morgan/no-negated-disjunction",
    ],
  },
  {
    "languageOptions": {},
    "name": "moso/node",
    "plugins": [
      "node",
    ],
    "rules": [
      "node/no-deprecated-api",
      "node/no-exports-assign",
      "node/no-extraneous-import",
      "node/no-extraneous-require",
      "node/no-missing-import",
      "- node/no-missing-require",
      "node/no-process-exit",
      "node/no-unpublished-import",
      "node/no-unpublished-require",
      "node/no-unsupported-features/es-builtins",
      "node/no-unsupported-features/es-syntax",
      "node/no-unsupported-features/node-builtins",
      "node/process-exit-as-throw",
      "node/hashbang",
      "- node/prefer-global/process",
      "node/prefer-global/text-decoder",
      "node/prefer-global/text-encoder",
      "node/prefer-global/url-search-params",
      "- node/no-top-level-await",
      "node/callback-return",
      "node/handle-callback-err",
      "node/no-callback-literal",
      "node/no-mixed-requires",
      "node/no-new-require",
      "node/no-path-concat",
      "node/no-restricted-import",
      "- node/no-restricted-require",
      "node/no-sync",
      "node/prefer-global/buffer",
      "node/prefer-global/console",
      "node/prefer-promises/dns",
      "node/prefer-promises/fs",
    ],
    "settings": {
      "node": {
        "version": "^22.22.2 || >=24",
      },
    },
  },
  {
    "files": [
      "**/?(.)*.d.?([cm])ts",
      "**/*.mjs",
      "**/*.?([cm])ts",
      "**/*.?([cm])tsx",
    ],
    "rules": [
      "- node/no-unsupported-features/es-syntax",
    ],
  },
  {
    "files": [
      "**/?(.)*.d.?([cm])ts",
      "**/*.?([cm])ts",
      "**/*.?([cm])tsx",
    ],
    "rules": [
      "- node/no-extraneous-import",
      "- node/no-missing-import",
      "- node/no-restricted-import",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
      "**/*.astro",
      "**/*.vue",
    ],
    "name": "moso/promise",
    "plugins": [
      "promise",
    ],
    "rules": [
      "promise/no-callback-in-promise",
      "promise/no-nesting",
      "promise/no-new-statics",
      "promise/no-promise-in-callback",
      "promise/no-return-in-finally",
      "promise/no-return-wrap",
      "promise/param-names",
      "promise/valid-params",
      "- promise/always-return",
      "- promise/avoid-new",
      "promise/catch-or-return",
      "- promise/no-native",
      "promise/prefer-catch",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
      "**/*.astro",
      "**/*.vue",
    ],
    "name": "moso/regexp",
    "plugins": [
      "regexp",
    ],
    "rules": [
      "- no-empty-character-class",
      "- no-invalid-regexp",
      "- no-useless-backreference",
      "no-control-regex",
      "no-misleading-character-class",
      "no-regex-spaces",
      "prefer-regex-literals",
      "regexp/confusing-quantifier",
      "regexp/control-character-escape",
      "regexp/match-any",
      "regexp/negation",
      "regexp/no-contradiction-with-assertion",
      "regexp/no-dupe-characters-character-class",
      "regexp/no-dupe-disjunctions",
      "regexp/no-empty-alternative",
      "regexp/no-empty-capturing-group",
      "regexp/no-empty-character-class",
      "regexp/no-empty-group",
      "regexp/no-empty-lookarounds-assertion",
      "regexp/no-empty-string-literal",
      "regexp/no-escape-backspace",
      "regexp/no-extra-lookaround-assertions",
      "regexp/no-invalid-regexp",
      "regexp/no-invisible-character",
      "regexp/no-lazy-ends",
      "regexp/no-legacy-features",
      "regexp/no-misleading-capturing-group",
      "regexp/no-misleading-unicode-character",
      "regexp/no-missing-g-flag",
      "regexp/no-non-standard-flag",
      "regexp/no-obscure-range",
      "regexp/no-optional-assertion",
      "regexp/no-potentially-useless-backreference",
      "regexp/no-super-linear-backtracking",
      "regexp/no-trivially-nested-assertion",
      "regexp/no-trivially-nested-quantifier",
      "regexp/no-unused-capturing-group",
      "regexp/no-useless-assertions",
      "regexp/no-useless-backreference",
      "regexp/no-useless-character-class",
      "regexp/no-useless-dollar-replacements",
      "regexp/no-useless-escape",
      "regexp/no-useless-flag",
      "regexp/no-useless-lazy",
      "regexp/no-useless-non-capturing-group",
      "regexp/no-useless-quantifier",
      "regexp/no-useless-range",
      "regexp/no-useless-set-operand",
      "regexp/no-useless-string-literal",
      "regexp/no-useless-two-nums-quantifier",
      "regexp/no-zero-quantifier",
      "regexp/optimal-lookaround-quantifier",
      "regexp/optimal-quantifier-concatenation",
      "regexp/prefer-character-class",
      "regexp/prefer-d",
      "regexp/prefer-plus-quantifier",
      "regexp/prefer-predefined-assertion",
      "regexp/prefer-question-quantifier",
      "regexp/prefer-range",
      "regexp/prefer-set-operation",
      "regexp/prefer-star-quantifier",
      "regexp/prefer-unicode-codepoint-escapes",
      "regexp/prefer-w",
      "regexp/simplify-set-operations",
      "regexp/sort-flags",
      "- regexp/strict",
      "regexp/use-ignore-case",
      "unicorn/better-regex",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
      "**/*.astro",
      "**/*.vue",
    ],
    "name": "moso/unicorn",
    "plugins": [
      "unicorn",
    ],
    "rules": [
      "unicorn/better-regex",
      "unicorn/catch-error-name",
      "unicorn/consistent-empty-array-spread",
      "unicorn/consistent-function-scoping",
      "unicorn/custom-error-definition",
      "unicorn/error-message",
      "unicorn/escape-case",
      "unicorn/new-for-builtins",
      "unicorn/no-anonymous-default-export",
      "unicorn/no-array-method-this-argument",
      "unicorn/no-await-expression-member",
      "unicorn/no-await-in-promise-methods",
      "unicorn/no-console-spaces",
      "unicorn/no-document-cookie",
      "unicorn/no-for-loop",
      "unicorn/no-hex-escape",
      "unicorn/no-instanceof-builtins",
      "unicorn/no-invalid-fetch-options",
      "unicorn/no-invalid-remove-event-listener",
      "unicorn/no-negated-condition",
      "unicorn/no-negation-in-equality-check",
      "unicorn/no-new-array",
      "unicorn/no-new-buffer",
      "unicorn/no-object-as-default-parameter",
      "unicorn/no-single-promise-in-promise-methods",
      "unicorn/no-static-only-class",
      "unicorn/no-thenable",
      "unicorn/no-this-assignment",
      "unicorn/no-typeof-undefined",
      "unicorn/no-unnecessary-array-flat-depth",
      "unicorn/no-unnecessary-await",
      "unicorn/no-unnecessary-polyfills",
      "unicorn/no-unreadable-array-destructuring",
      "unicorn/no-unreadable-iife",
      "unicorn/no-useless-fallback-in-spread",
      "unicorn/no-useless-length-check",
      "unicorn/no-useless-promise-resolve-reject",
      "unicorn/no-useless-switch-case",
      "unicorn/no-zero-fractions",
      "unicorn/number-literal-case",
      "unicorn/numeric-separators-style",
      "unicorn/prefer-add-event-listener",
      "unicorn/prefer-array-find",
      "unicorn/prefer-array-flat",
      "unicorn/prefer-array-index-of",
      "unicorn/prefer-array-some",
      "unicorn/prefer-at",
      "unicorn/prefer-blob-reading-methods",
      "unicorn/prefer-date-now",
      "unicorn/prefer-default-parameters",
      "unicorn/prefer-dom-node-append",
      "unicorn/prefer-dom-node-dataset",
      "unicorn/prefer-dom-node-remove",
      "unicorn/prefer-dom-node-text-content",
      "unicorn/prefer-event-target",
      "unicorn/prefer-export-from",
      "unicorn/prefer-import-meta-properties",
      "unicorn/prefer-includes",
      "unicorn/prefer-keyboard-event-key",
      "unicorn/prefer-logical-operator-over-ternary",
      "unicorn/prefer-modern-dom-apis",
      "unicorn/prefer-modern-math-apis",
      "unicorn/prefer-module",
      "unicorn/prefer-native-coercion-functions",
      "unicorn/prefer-node-protocol",
      "unicorn/prefer-number-properties",
      "unicorn/prefer-object-from-entries",
      "unicorn/prefer-optional-catch-binding",
      "unicorn/prefer-query-selector",
      "unicorn/prefer-reflect-apply",
      "unicorn/prefer-regexp-test",
      "unicorn/prefer-single-call",
      "unicorn/prefer-spread",
      "unicorn/prefer-string-replace-all",
      "unicorn/prefer-string-slice",
      "unicorn/prefer-string-starts-ends-with",
      "unicorn/prefer-switch",
      "unicorn/prefer-ternary",
      "- unicorn/prefer-top-level-await",
      "unicorn/prefer-type-error",
      "unicorn/require-array-join-separator",
      "unicorn/require-number-to-fixed-digits-argument",
      "unicorn/switch-case-braces",
      "unicorn/throw-new-error",
    ],
  },
  {
    "files": [
      "**/*.astro",
    ],
    "languageOptions": {
      "parser": "astro-eslint-parser",
      "parserOptions": {
        "extraFileExtensions": [
          ".astro",
        ],
      },
      "sourceType": "module",
    },
    "name": "moso/astro/setup",
    "plugins": [
      "astro",
    ],
    "processor": "astro/client-side-ts",
  },
  {
    "files": [
      "**/*.astro",
    ],
    "name": "moso/astro/rules",
    "rules": [
      "- @moso/no-top-level-await",
      "- node/no-top-level-await",
      "- prettier/prettier",
      "astro/missing-client-only-directive-value",
      "astro/no-conflict-set-directives",
      "astro/no-deprecated-astro-canonicalurl",
      "astro/no-deprecated-astro-fetchcontent",
      "astro/no-deprecated-astro-resolve",
      "astro/no-deprecated-getentrybyslug",
      "astro/no-exports-from-components",
      "astro/no-omitted-end-tags",
      "astro/no-prerender-export-outside-pages",
      "astro/no-unused-define-vars-in-style",
      "astro/valid-compile",
      "astro/no-set-html-directive",
      "astro/no-set-text-directive",
      "astro/no-unsafe-inline-scripts",
      "astro/no-unused-css-selector",
      "astro/prefer-class-list-directive",
      "astro/prefer-object-class-list",
      "astro/prefer-split-class-list",
      "- astro/sort-attributes",
      "- @stylistic/indent",
      "- @stylistic/jsx-closing-tag-location",
      "- @stylistic/jsx-one-expression-per-line",
      "- @stylistic/no-multiple-empty-lines",
      "- semi",
      "astro/semi",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
      "**/*.astro",
      "**/*.vue",
    ],
    "name": "moso/e18e/rules",
    "plugins": [
      "e18e",
    ],
    "rules": [
      "e18e/prefer-array-at",
      "e18e/prefer-array-fill",
      "e18e/prefer-includes",
      "e18e/prefer-array-to-reversed",
      "e18e/prefer-array-to-sorted",
      "e18e/prefer-array-to-spliced",
      "e18e/prefer-nullish-coalescing",
      "e18e/prefer-object-has-own",
      "e18e/prefer-spread-syntax",
      "e18e/prefer-url-canparse",
      "e18e/prefer-array-from-map",
      "e18e/prefer-timer-args",
      "e18e/prefer-date-now",
      "e18e/prefer-regex-test",
      "e18e/prefer-array-some",
      "e18e/prefer-static-regex",
      "e18e/prefer-string-fromcharcode",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
      "**/*.astro",
      "**/*.vue",
    ],
    "name": "moso/e18e/library-disables",
    "rules": [
      "- e18e/prefer-static-regex",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
      "**/*.astro",
      "**/*.vue",
    ],
    "name": "moso/functional",
    "plugins": [
      "functional",
    ],
    "rules": [
      "functional/functional-parameters",
      "functional/immutable-data",
      "- functional/no-classes",
      "functional/no-class-inheritance",
      "- functional/no-conditional-statements",
      "- functional/no-expression-statements",
      "functional/no-let",
      "functional/no-loop-statements",
      "functional/no-mixed-types",
      "- functional/no-promise-reject",
      "- functional/no-return-void",
      "- functional/no-this-expressions",
      "functional/no-throw-statements",
      "- functional/no-try-statements",
      "- functional/prefer-immutable-types",
      "functional/prefer-property-signatures",
      "- functional/prefer-readonly-type",
      "functional/prefer-tacit",
      "functional/readonly-type",
      "- functional/type-declaration-immutability",
      "- @typescript-eslint/prefer-readonly-parameter-types",
    ],
    "settings": {
      "immutability": {
        "overrides": [
          {
            "to": "ReadonlyShallow",
            "type": "^Readonly<.+>$",
          },
          {
            "to": "ReadonlyDeep",
            "type": "^ReadonlyDeep<.+>$",
          },
          {
            "to": "Immutable",
            "type": "^Immutable<.+>$",
          },
        ],
      },
    },
  },
  {
    "name": "moso/jsdoc",
    "plugins": [
      "jsdoc",
    ],
    "rules": [
      "jsdoc/check-access",
      "jsdoc/check-alignment",
      "jsdoc/check-param-names",
      "jsdoc/check-property-names",
      "jsdoc/check-tag-names",
      "jsdoc/check-types",
      "jsdoc/check-values",
      "jsdoc/empty-tags",
      "jsdoc/implements-on-classes",
      "jsdoc/multiline-blocks",
      "jsdoc/no-defaults",
      "jsdoc/no-multi-asterisks",
      "jsdoc/no-undefined-types",
      "jsdoc/reject-any-type",
      "jsdoc/reject-function-type",
      "jsdoc/require-jsdoc",
      "jsdoc/require-next-type",
      "jsdoc/require-param",
      "jsdoc/require-param-description",
      "jsdoc/require-param-name",
      "jsdoc/require-property",
      "jsdoc/require-property-description",
      "jsdoc/require-property-name",
      "jsdoc/require-returns",
      "jsdoc/require-returns-check",
      "jsdoc/require-returns-description",
      "jsdoc/require-throws-type",
      "jsdoc/require-yields",
      "jsdoc/require-yields-check",
      "jsdoc/require-yields-type",
      "jsdoc/tag-lines",
      "jsdoc/valid-types",
      "jsdoc/check-indentation",
      "jsdoc/check-line-alignment",
      "jsdoc/no-bad-blocks",
      "jsdoc/no-types",
      "jsdoc/require-asterisk-prefix",
      "jsdoc/require-description",
      "jsdoc/require-hyphen-before-param-description",
      "jsdoc/require-throws",
      "jsdoc/require-throws-description",
      "jsdoc/require-yields-description",
      "- jsdoc/sort-tags",
    ],
  },
  {
    "files": [
      "**/*.json",
      "**/*.json5",
      "**/*.jsonc",
    ],
    "languageOptions": {
      "parser": "jsonc-eslint-parser",
    },
    "name": "moso/jsonc",
    "plugins": [
      "jsonc",
    ],
    "rules": [
      "jsonc/no-bigint-literals",
      "jsonc/no-binary-expression",
      "jsonc/no-binary-numeric-literals",
      "jsonc/no-dupe-keys",
      "jsonc/no-escape-sequence-in-identifier",
      "jsonc/no-floating-decimal",
      "jsonc/no-hexadecimal-numeric-literals",
      "jsonc/no-infinity",
      "jsonc/no-multi-str",
      "jsonc/no-nan",
      "jsonc/no-number-props",
      "jsonc/no-numeric-separators",
      "jsonc/no-octal",
      "jsonc/no-octal-escape",
      "jsonc/no-octal-numeric-literals",
      "jsonc/no-parenthesized",
      "jsonc/no-plus-sign",
      "jsonc/no-regexp-literals",
      "jsonc/no-sparse-arrays",
      "jsonc/no-template-literals",
      "jsonc/no-undefined-value",
      "jsonc/no-unicode-codepoint-escapes",
      "jsonc/no-useless-escape",
      "jsonc/space-unary-ops",
      "jsonc/valid-json-number",
      "jsonc/vue-custom-block/no-parsing-error",
      "jsonc/array-bracket-spacing",
      "jsonc/comma-dangle",
      "jsonc/comma-style",
      "jsonc/indent",
      "jsonc/key-spacing",
      "jsonc/object-curly-newline",
      "jsonc/object-curly-spacing",
      "jsonc/object-property-newline",
      "jsonc/quote-props",
      "jsonc/quotes",
    ],
  },
  {
    "files": [
      "**/package.json",
    ],
    "name": "moso/sort/package-json",
    "rules": [
      "jsonc/sort-array-values",
      "jsonc/sort-keys",
    ],
  },
  {
    "files": [
      "**/tsconfig.json",
      "**/tsconfig.*.json",
    ],
    "name": "moso/sort/tsconfig-json",
    "rules": [
      "jsonc/sort-keys",
    ],
  },
  {
    "files": [
      "**/*.?([cm])jsx",
      "**/*.?([cm])tsx",
    ],
    "languageOptions": {
      "parserOptions": {
        "ecmaFeatures": {
          "jsx": true,
        },
      },
    },
    "name": "moso/jsx/setup",
  },
  {
    "name": "moso/jsx/rules",
    "rules": [
      "@stylistic/jsx-curly-spacing",
      "- @stylistic/jsx-one-expression-per-line",
    ],
  },
  {
    "name": "moso/jsx/a11y",
    "plugins": [
      "jsx-a11y",
    ],
    "rules": [
      "jsx-a11y/alt-text",
      "jsx-a11y/aria-props",
      "jsx-a11y/aria-proptypes",
      "jsx-a11y/aria-role",
      "jsx-a11y/aria-unsupported-elements",
      "jsx-a11y/iframe-has-title",
      "jsx-a11y/no-access-key",
      "jsx-a11y/no-static-element-interactions",
      "jsx-a11y/role-has-required-aria-props",
      "jsx-a11y/role-supports-aria-props",
      "jsx-a11y/tabindex-no-positive",
      "- jsx-a11y/anchor-ambiguous-text",
      "jsx-a11y/interactive-supports-focus",
      "- jsx-a11y/label-has-for",
      "jsx-a11y/no-noninteractive-element-interactions",
    ],
  },
  {
    "languageOptions": {
      "parserOptions": {
        "ecmaFeatures": {
          "jsx": true,
        },
      },
      "sourceType": "module",
    },
    "name": "moso/nextjs/setup",
    "plugins": [
      "@next/next",
    ],
    "settings": {
      "react": {
        "version": "detect",
      },
    },
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
    ],
    "name": "moso/nextjs/rules",
    "rules": [
      "@next/next/google-font-display",
      "@next/next/google-font-preconnect",
      "@next/next/next-script-for-ga",
      "@next/next/no-async-client-component",
      "@next/next/no-before-interactive-script-outside-document",
      "@next/next/no-css-tags",
      "@next/next/no-head-element",
      "@next/next/no-html-link-for-pages",
      "@next/next/no-img-element",
      "@next/next/no-page-custom-font",
      "@next/next/no-styled-jsx-in-document",
      "@next/next/no-sync-scripts",
      "@next/next/no-title-in-document-head",
      "@next/next/no-typos",
      "@next/next/no-unwanted-polyfillio",
      "@next/next/inline-script-id",
      "@next/next/no-assign-module-variable",
      "@next/next/no-document-import-in-page",
      "@next/next/no-duplicate-head",
      "@next/next/no-head-import-in-document",
      "@next/next/no-script-component-in-head",
    ],
  },
  {
    "name": "moso/perfectionist",
    "plugins": [
      "perfectionist",
    ],
    "rules": [
      "perfectionist/sort-array-includes",
      "perfectionist/sort-classes",
      "perfectionist/sort-decorators",
      "perfectionist/sort-enums",
      "perfectionist/sort-export-attributes",
      "perfectionist/sort-exports",
      "perfectionist/sort-heritage-clauses",
      "perfectionist/sort-import-attributes",
      "perfectionist/sort-imports",
      "perfectionist/sort-interfaces",
      "perfectionist/sort-intersection-types",
      "perfectionist/sort-jsx-props",
      "perfectionist/sort-maps",
      "perfectionist/sort-modules",
      "perfectionist/sort-named-exports",
      "perfectionist/sort-named-imports",
      "perfectionist/sort-object-types",
      "perfectionist/sort-objects",
      "perfectionist/sort-sets",
      "perfectionist/sort-switch-case",
      "perfectionist/sort-union-types",
      "perfectionist/sort-variable-declarations",
    ],
  },
  {
    "files": [
      "**/*.?([cm])jsx",
      "**/*.?([cm])ts",
      "**/*.?([cm])tsx",
    ],
    "languageOptions": {
      "parser": "typescript-eslint/parser",
      "parserOptions": {
        "ecmaFeatures": {
          "jsx": true,
        },
      },
      "sourceType": "module",
    },
    "name": "moso/react",
    "plugins": [
      "@eslint-react",
      "react-hooks",
      "react-refresh",
      "react-you-might-not-need-an-effect",
    ],
    "rules": [
      "@eslint-react/error-boundaries",
      "@eslint-react/exhaustive-deps",
      "@eslint-react/no-access-state-in-setstate",
      "@eslint-react/no-array-index-key",
      "@eslint-react/no-children-count",
      "@eslint-react/no-children-for-each",
      "@eslint-react/no-children-map",
      "@eslint-react/no-children-only",
      "@eslint-react/no-children-to-array",
      "@eslint-react/no-clone-element",
      "@eslint-react/no-component-will-mount",
      "@eslint-react/no-component-will-receive-props",
      "@eslint-react/no-component-will-update",
      "@eslint-react/no-context-provider",
      "@eslint-react/no-create-ref",
      "@eslint-react/no-direct-mutation-state",
      "@eslint-react/no-forward-ref",
      "@eslint-react/no-missing-key",
      "@eslint-react/no-nested-component-definitions",
      "@eslint-react/no-nested-lazy-component-declarations",
      "@eslint-react/no-set-state-in-component-did-mount",
      "@eslint-react/no-set-state-in-component-did-update",
      "@eslint-react/no-set-state-in-component-will-update",
      "@eslint-react/no-unnecessary-use-prefix",
      "@eslint-react/no-unsafe-component-will-mount",
      "@eslint-react/no-unsafe-component-will-receive-props",
      "@eslint-react/no-unsafe-component-will-update",
      "@eslint-react/no-unused-class-component-members",
      "@eslint-react/no-use-context",
      "@eslint-react/purity",
      "@eslint-react/rules-of-hooks",
      "@eslint-react/set-state-in-effect",
      "@eslint-react/set-state-in-render",
      "@eslint-react/static-components",
      "@eslint-react/unsupported-syntax",
      "@eslint-react/use-memo",
      "@eslint-react/use-state",
      "@eslint-react/jsx-no-children-prop",
      "@eslint-react/jsx-no-children-prop-with-children",
      "@eslint-react/jsx-no-comment-textnodes",
      "@eslint-react/jsx-no-key-after-spread",
      "@eslint-react/jsx-no-leaked-dollar",
      "@eslint-react/jsx-no-leaked-semicolon",
      "@eslint-react/jsx-no-namespace",
      "@eslint-react/rsc-function-definition",
      "@eslint-react/dom-no-dangerously-set-innerhtml",
      "@eslint-react/dom-no-dangerously-set-innerhtml-with-children",
      "@eslint-react/dom-no-find-dom-node",
      "@eslint-react/dom-no-flush-sync",
      "@eslint-react/dom-no-hydrate",
      "@eslint-react/dom-no-render",
      "@eslint-react/dom-no-render-return-value",
      "@eslint-react/dom-no-script-url",
      "@eslint-react/dom-no-unsafe-iframe-sandbox",
      "@eslint-react/dom-no-use-form-state",
      "@eslint-react/dom-no-void-elements-with-children",
      "@eslint-react/web-api-no-leaked-event-listener",
      "@eslint-react/web-api-no-leaked-fetch",
      "@eslint-react/web-api-no-leaked-intersection-observer",
      "@eslint-react/web-api-no-leaked-interval",
      "@eslint-react/web-api-no-leaked-resize-observer",
      "@eslint-react/web-api-no-leaked-timeout",
      "@eslint-react/naming-convention-context-name",
      "@eslint-react/naming-convention-id-name",
      "@eslint-react/naming-convention-ref-name",
      "@eslint-react/no-class-component",
      "@eslint-react/no-misused-capture-owner-stack",
      "@eslint-react/no-unstable-context-value",
      "@eslint-react/no-unstable-default-props",
      "@eslint-react/jsx-no-useless-fragment",
      "@eslint-react/dom-no-missing-button-type",
      "@eslint-react/dom-no-missing-iframe-sandbox",
      "@eslint-react/dom-no-unsafe-target-blank",
      "react-you-might-not-need-an-effect/no-derived-state",
      "react-you-might-not-need-an-effect/no-chain-state-updates",
      "react-you-might-not-need-an-effect/no-event-handler",
      "react-you-might-not-need-an-effect/no-adjust-state-on-prop-change",
      "react-you-might-not-need-an-effect/no-reset-all-state-on-prop-change",
      "react-you-might-not-need-an-effect/no-pass-live-state-to-parent",
      "react-you-might-not-need-an-effect/no-pass-data-to-parent",
      "react-you-might-not-need-an-effect/no-external-store-subscription",
      "react-you-might-not-need-an-effect/no-initialize-state",
      "react-hooks/globals",
      "react-hooks/immutability",
      "react-hooks/purity",
      "react-hooks/refs",
      "- react-hooks/set-state-in-effect",
      "react-hooks/set-state-in-render",
      "react-hooks/static-components",
      "react-hooks/unsupported-syntax",
      "react-hooks/use-memo",
      "@stylistic/jsx-closing-bracket-location",
      "@stylistic/jsx-curly-brace-presence",
      "@stylistic/jsx-first-prop-new-line",
      "@stylistic/jsx-pascal-case",
      "@stylistic/jsx-self-closing-comp",
      "@stylistic/jsx-tag-spacing",
      "@stylistic/jsx-wrap-multilines",
      "@stylistic/no-multi-spaces",
      "react-hooks/exhaustive-deps",
      "react-hooks/rules-of-hooks",
      "react-refresh/only-export-components",
    ],
    "settings": {
      "@eslint-react": {
        "version": "detect",
      },
    },
  },
  {
    "files": [
      "**/?(.)*.d.?([cm])ts",
      "**/*.?([cm])jsx",
      "**/*.?([cm])ts",
      "**/*.?([cm])tsx",
    ],
    "name": "moso/react/typescript",
    "rules": [
      "- @eslint-react/dom-no-string-style-prop",
      "- @eslint-react/dom-no-unknown-property",
    ],
  },
  {
    "files": [
      "**/?(.)*.d.?([cm])ts",
      "**/*.?([cm])jsx",
      "**/*.?([cm])ts",
      "**/*.?([cm])tsx",
    ],
    "ignores": [
      "**/*.astro/*.ts",
      "**/*.md/**",
    ],
    "name": "moso/react/typescript/type-aware-rules",
    "rules": [
      "@eslint-react/error-boundaries",
      "@eslint-react/exhaustive-deps",
      "@eslint-react/no-access-state-in-setstate",
      "@eslint-react/no-array-index-key",
      "@eslint-react/no-children-count",
      "@eslint-react/no-children-for-each",
      "@eslint-react/no-children-map",
      "@eslint-react/no-children-only",
      "@eslint-react/no-children-to-array",
      "@eslint-react/no-clone-element",
      "@eslint-react/no-component-will-mount",
      "@eslint-react/no-component-will-receive-props",
      "@eslint-react/no-component-will-update",
      "@eslint-react/no-context-provider",
      "@eslint-react/no-create-ref",
      "@eslint-react/no-direct-mutation-state",
      "@eslint-react/no-forward-ref",
      "@eslint-react/no-missing-key",
      "@eslint-react/no-nested-component-definitions",
      "@eslint-react/no-nested-lazy-component-declarations",
      "@eslint-react/no-set-state-in-component-did-mount",
      "@eslint-react/no-set-state-in-component-did-update",
      "@eslint-react/no-set-state-in-component-will-update",
      "@eslint-react/no-unnecessary-use-prefix",
      "@eslint-react/no-unsafe-component-will-mount",
      "@eslint-react/no-unsafe-component-will-receive-props",
      "@eslint-react/no-unsafe-component-will-update",
      "@eslint-react/no-unused-class-component-members",
      "@eslint-react/no-use-context",
      "@eslint-react/purity",
      "@eslint-react/rules-of-hooks",
      "@eslint-react/set-state-in-effect",
      "@eslint-react/set-state-in-render",
      "@eslint-react/static-components",
      "@eslint-react/unsupported-syntax",
      "@eslint-react/use-memo",
      "@eslint-react/use-state",
      "@eslint-react/jsx-no-children-prop",
      "@eslint-react/jsx-no-children-prop-with-children",
      "@eslint-react/jsx-no-comment-textnodes",
      "@eslint-react/jsx-no-key-after-spread",
      "@eslint-react/jsx-no-leaked-dollar",
      "@eslint-react/jsx-no-leaked-semicolon",
      "@eslint-react/jsx-no-namespace",
      "@eslint-react/rsc-function-definition",
      "@eslint-react/dom-no-dangerously-set-innerhtml",
      "@eslint-react/dom-no-dangerously-set-innerhtml-with-children",
      "@eslint-react/dom-no-find-dom-node",
      "@eslint-react/dom-no-flush-sync",
      "@eslint-react/dom-no-hydrate",
      "@eslint-react/dom-no-render",
      "@eslint-react/dom-no-render-return-value",
      "@eslint-react/dom-no-script-url",
      "@eslint-react/dom-no-unsafe-iframe-sandbox",
      "@eslint-react/dom-no-use-form-state",
      "@eslint-react/dom-no-void-elements-with-children",
      "@eslint-react/web-api-no-leaked-event-listener",
      "@eslint-react/web-api-no-leaked-fetch",
      "@eslint-react/web-api-no-leaked-intersection-observer",
      "@eslint-react/web-api-no-leaked-interval",
      "@eslint-react/web-api-no-leaked-resize-observer",
      "@eslint-react/web-api-no-leaked-timeout",
      "@eslint-react/naming-convention-context-name",
      "@eslint-react/naming-convention-id-name",
      "@eslint-react/naming-convention-ref-name",
      "@eslint-react/no-class-component",
      "@eslint-react/no-misused-capture-owner-stack",
      "@eslint-react/no-unstable-context-value",
      "@eslint-react/no-unstable-default-props",
      "@eslint-react/jsx-no-useless-fragment",
      "@eslint-react/dom-no-missing-button-type",
      "@eslint-react/dom-no-missing-iframe-sandbox",
      "@eslint-react/dom-no-unsafe-target-blank",
      "@eslint-react/no-leaked-conditional-rendering",
      "@eslint-react/no-unused-props",
      "react-hooks/exhaustive-deps",
      "@typescript-eslint/class-methods-use-this",
    ],
  },
  {
    "name": "moso/stylistic",
    "plugins": [
      "@stylistic",
    ],
    "rules": [
      "@stylistic/array-bracket-spacing",
      "@stylistic/arrow-parens",
      "@stylistic/arrow-spacing",
      "@stylistic/block-spacing",
      "@stylistic/brace-style",
      "@stylistic/comma-dangle",
      "@stylistic/comma-spacing",
      "@stylistic/comma-style",
      "@stylistic/computed-property-spacing",
      "@stylistic/dot-location",
      "@stylistic/eol-last",
      "@stylistic/generator-star-spacing",
      "- @stylistic/indent",
      "@stylistic/indent-binary-ops",
      "@stylistic/key-spacing",
      "@stylistic/keyword-spacing",
      "@stylistic/lines-between-class-members",
      "@stylistic/max-statements-per-line",
      "@stylistic/member-delimiter-style",
      "@stylistic/multiline-ternary",
      "@stylistic/new-parens",
      "- @stylistic/no-extra-parens",
      "@stylistic/no-floating-decimal",
      "@stylistic/no-mixed-operators",
      "@stylistic/no-mixed-spaces-and-tabs",
      "@stylistic/no-multi-spaces",
      "@stylistic/no-multiple-empty-lines",
      "@stylistic/no-tabs",
      "@stylistic/no-trailing-spaces",
      "@stylistic/no-whitespace-before-property",
      "@stylistic/object-curly-spacing",
      "@stylistic/operator-linebreak",
      "@stylistic/padded-blocks",
      "@stylistic/quote-props",
      "@stylistic/quotes",
      "@stylistic/rest-spread-spacing",
      "@stylistic/semi",
      "@stylistic/semi-spacing",
      "@stylistic/space-before-blocks",
      "@stylistic/space-before-function-paren",
      "@stylistic/space-in-parens",
      "@stylistic/space-infix-ops",
      "@stylistic/space-unary-ops",
      "@stylistic/spaced-comment",
      "@stylistic/template-curly-spacing",
      "@stylistic/template-tag-spacing",
      "@stylistic/type-annotation-spacing",
      "@stylistic/type-generic-spacing",
      "@stylistic/type-named-tuple-spacing",
      "@stylistic/wrap-iife",
      "@stylistic/yield-star-spacing",
      "@stylistic/jsx-closing-bracket-location",
      "@stylistic/jsx-closing-tag-location",
      "@stylistic/jsx-curly-brace-presence",
      "@stylistic/jsx-curly-newline",
      "@stylistic/jsx-curly-spacing",
      "@stylistic/jsx-equals-spacing",
      "@stylistic/jsx-first-prop-new-line",
      "@stylistic/jsx-function-call-newline",
      "@stylistic/jsx-indent-props",
      "@stylistic/jsx-max-props-per-line",
      "@stylistic/jsx-one-expression-per-line",
      "@stylistic/jsx-quotes",
      "@stylistic/jsx-tag-spacing",
      "@stylistic/jsx-wrap-multilines",
      "@stylistic/array-element-newline",
      "@stylistic/function-call-argument-newline",
      "@stylistic/function-paren-newline",
      "@stylistic/lines-around-comment",
      "@stylistic/no-confusing-arrow",
      "@stylistic/object-curly-newline",
      "@stylistic/object-property-newline",
      "@stylistic/one-var-declaration-per-line",
      "@stylistic/wrap-regex",
    ],
  },
  {
    "languageOptions": {},
    "name": "moso/test/setup",
    "plugins": [
      "no-only-tests",
      "vitest",
    ],
    "settings": {
      "vitest": {
        "typecheck": true,
      },
    },
  },
  {
    "files": [
      "**/__tests__/**/?(.)*.?([cm])[jt]s?(x)",
      "**/?(.)*.spec.?([cm])[jt]s?(x)",
      "**/?(.)*.test.?([cm])[jt]s?(x)",
      "**/?(.)*.bench.?([cm])[jt]s?(x)",
      "**/?(.)*.benchmark.?([cm])[jt]s?(x)",
    ],
    "name": "moso/test/rules",
    "rules": [
      "- functional/functional-parameters",
      "- functional/immutable-data",
      "- functional/no-classes",
      "- functional/no-class-inheritance",
      "- functional/no-conditional-statements",
      "- functional/no-expression-statements",
      "- functional/no-let",
      "- functional/no-loop-statements",
      "- functional/no-mixed-types",
      "- functional/no-promise-reject",
      "- functional/no-return-void",
      "- functional/no-this-expressions",
      "- functional/no-throw-statements",
      "- functional/no-try-statements",
      "- functional/prefer-immutable-types",
      "- functional/prefer-property-signatures",
      "- functional/prefer-readonly-type",
      "- functional/prefer-tacit",
      "- functional/readonly-type",
      "- functional/type-declaration-immutability",
      "- @moso/no-top-level-await",
      "- jsdoc/require-jsdoc",
      "- node/no-sync",
      "- node/prefer-global/process",
      "- regexp/no-super-linear-backtracking",
      "- unicorn/consistent-function-scoping",
      "- unicorn/prefer-module",
      "- @typescript-eslint/consistent-type-definitions",
      "- @typescript-eslint/no-unsafe-argument",
      "- @typescript-eslint/no-unsafe-assignment",
      "- @typescript-eslint/no-unsafe-call",
      "- @typescript-eslint/no-unsafe-member-access",
      "- @typescript-eslint/no-unsafe-return",
      "- @typescript-eslint/no-unused-expressions",
      "- @typescript-eslint/no-unused-vars",
      "- @typescript-eslint/strict-boolean-expressions",
      "no-only-tests/no-only-tests",
      "vitest/expect-expect",
      "vitest/no-commented-out-tests",
      "vitest/no-conditional-expect",
      "vitest/no-disabled-tests",
      "vitest/no-focused-tests",
      "vitest/no-identical-title",
      "vitest/no-import-node-test",
      "vitest/no-interpolation-in-snapshots",
      "vitest/no-mocks-import",
      "vitest/no-standalone-expect",
      "vitest/no-unneeded-async-expect-function",
      "vitest/prefer-called-exactly-once-with",
      "vitest/require-local-test-context-for-concurrent-snapshots",
      "vitest/valid-describe-callback",
      "- vitest/valid-expect",
      "vitest/valid-expect-in-promise",
      "- vitest/valid-title",
      "vitest/consistent-test-it",
      "vitest/prefer-hooks-in-order",
      "vitest/prefer-lowercase-title",
    ],
  },
  {
    "name": "moso/toml/setup",
    "plugins": [
      "toml",
    ],
  },
  {
    "files": [
      "**/*.toml",
    ],
    "languageOptions": {
      "parser": "toml-eslint-parser",
    },
    "name": "moso/toml/rules",
    "rules": [
      "- @stylistic/spaced-comment",
      "toml/comma-style",
      "toml/keys-order",
      "toml/no-space-dots",
      "toml/no-unreadable-number-separator",
      "toml/precision-of-fractional-seconds",
      "toml/precision-of-integer",
      "toml/tables-order",
      "toml/vue-custom-block/no-parsing-error",
      "toml/array-bracket-newline",
      "toml/array-bracket-spacing",
      "toml/array-element-newline",
      "toml/indent",
      "toml/inline-table-curly-spacing",
      "toml/key-spacing",
      "toml/padding-line-between-pairs",
      "toml/padding-line-between-tables",
      "toml/quoted-keys",
      "toml/spaced-comment",
      "toml/table-bracket-spacing",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
      "**/*.vue",
    ],
    "languageOptions": {
      "parser": "typescript-eslint/parser",
      "parserOptions": {
        "ecmaFeatures": {
          "jsx": true,
        },
        "ecmaVersion": "latest",
        "extraFileExtensions": [
          "**/*.vue",
        ],
        "jsxPragma": undefined,
        "sourceType": "module",
        "warnOnUnsupportedTypeScriptVersion": true,
      },
    },
    "name": "moso/typescript/setup",
    "plugins": [
      "@typescript-eslint",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
      "**/*.vue",
    ],
    "name": "moso/typescript/rules",
    "rules": [
      "- constructor-super",
      "- getter-return",
      "- no-class-assign",
      "- no-const-assign",
      "- no-dupe-args",
      "- no-dupe-class-members",
      "- no-dupe-keys",
      "- no-func-assign",
      "- no-import-assign",
      "- no-new-native-nonconstructor",
      "- no-new-symbol",
      "- no-obj-calls",
      "- no-redeclare",
      "- no-setter-return",
      "- no-this-before-super",
      "- no-undef",
      "- no-unreachable",
      "- no-unsafe-negation",
      "no-var",
      "- no-with",
      "prefer-const",
      "prefer-rest-params",
      "prefer-spread",
      "@typescript-eslint/ban-ts-comment",
      "- no-array-constructor",
      "@typescript-eslint/no-array-constructor",
      "@typescript-eslint/no-duplicate-enum-values",
      "@typescript-eslint/no-empty-object-type",
      "@typescript-eslint/no-explicit-any",
      "@typescript-eslint/no-extra-non-null-assertion",
      "@typescript-eslint/no-misused-new",
      "@typescript-eslint/no-namespace",
      "@typescript-eslint/no-non-null-asserted-optional-chain",
      "@typescript-eslint/no-require-imports",
      "@typescript-eslint/no-this-alias",
      "@typescript-eslint/no-unnecessary-type-constraint",
      "@typescript-eslint/no-unsafe-declaration-merging",
      "@typescript-eslint/no-unsafe-function-type",
      "- no-unused-expressions",
      "@typescript-eslint/no-unused-expressions",
      "- no-unused-vars",
      "@typescript-eslint/no-unused-vars",
      "@typescript-eslint/no-wrapper-object-types",
      "@typescript-eslint/prefer-as-const",
      "@typescript-eslint/prefer-namespace-keyword",
      "@typescript-eslint/triple-slash-reference",
      "- class-methods-use-this",
      "- consistent-return",
      "- no-extra-boolean-cast",
      "- no-implied-eval",
      "- no-invalid-this",
      "- no-loop-func",
      "- no-loss-of-precision",
      "- no-use-before-define",
      "- no-useless-constructor",
      "@typescript-eslint/no-dynamic-delete",
      "@typescript-eslint/no-extraneous-class",
      "@typescript-eslint/no-invalid-void-type",
      "@typescript-eslint/no-non-null-asserted-nullish-coalescing",
      "@typescript-eslint/no-non-null-assertion",
      "@typescript-eslint/no-useless-constructor",
      "@typescript-eslint/prefer-literal-enum-member",
      "@typescript-eslint/unified-signatures",
      "@moso/no-force-cast-via-top-type",
      "@typescript-eslint/consistent-type-definitions",
      "@typescript-eslint/adjacent-overload-signatures",
      "@typescript-eslint/array-type",
      "@typescript-eslint/ban-tslint-comment",
      "@typescript-eslint/class-literal-property-style",
      "@typescript-eslint/consistent-generic-constructors",
      "@typescript-eslint/consistent-indexed-object-style",
      "@typescript-eslint/consistent-type-assertions",
      "@typescript-eslint/no-confusing-non-null-assertion",
      "- no-empty-function",
      "@typescript-eslint/no-empty-function",
      "@typescript-eslint/no-inferrable-types",
      "@typescript-eslint/prefer-for-of",
      "@typescript-eslint/prefer-function-type",
      "@stylistic/type-annotation-spacing",
      "@typescript-eslint/class-methods-use-this",
      "@typescript-eslint/consistent-type-imports",
      "@typescript-eslint/explicit-function-return-type",
      "- @typescript-eslint/explicit-member-accessibility",
      "@typescript-eslint/method-signature-style",
      "- @typescript-eslint/no-dupe-class-members",
      "@typescript-eslint/no-import-type-side-effects",
      "- @typescript-eslint/no-invalid-this",
      "@typescript-eslint/no-loop-func",
      "@typescript-eslint/no-use-before-define",
      "- @typescript-eslint/parameter-properties",
      "functional/no-mixed-types",
      "functional/prefer-property-signatures",
      "functional/readonly-type",
      "functional/type-declaration-immutability",
      "@typescript-eslint/naming-convention",
    ],
  },
  {
    "name": "moso/typescript/erasable-syntax",
    "plugins": [
      "erasable-syntax-only",
    ],
    "rules": [
      "erasable-syntax-only/enums",
      "erasable-syntax-only/import-aliases",
      "erasable-syntax-only/namespaces",
      "erasable-syntax-only/parameter-properties",
    ],
  },
  {
    "files": [
      "**/?(.)*.d.?([cm])ts",
      "**/*.?([cm])ts",
      "**/*.?([cm])tsx",
    ],
    "languageOptions": {
      "parser": "typescript-eslint/parser",
      "parserOptions": {
        "ecmaFeatures": {
          "jsx": true,
        },
        "ecmaVersion": "latest",
        "extraFileExtensions": [
          "**/*.vue",
        ],
        "jsxPragma": undefined,
        "sourceType": "module",
        "warnOnUnsupportedTypeScriptVersion": true,
      },
    },
    "name": "moso/typescript/rules-type-aware",
    "rules": [
      "@typescript-eslint/await-thenable",
      "@typescript-eslint/no-array-delete",
      "@typescript-eslint/no-base-to-string",
      "@typescript-eslint/no-duplicate-type-constituents",
      "@typescript-eslint/no-floating-promises",
      "@typescript-eslint/no-for-in-array",
      "- no-implied-eval",
      "@typescript-eslint/no-implied-eval",
      "@typescript-eslint/no-misused-promises",
      "@typescript-eslint/no-redundant-type-constituents",
      "@typescript-eslint/no-unnecessary-type-assertion",
      "@typescript-eslint/no-unsafe-argument",
      "@typescript-eslint/no-unsafe-assignment",
      "@typescript-eslint/no-unsafe-call",
      "@typescript-eslint/no-unsafe-enum-comparison",
      "@typescript-eslint/no-unsafe-member-access",
      "@typescript-eslint/no-unsafe-return",
      "@typescript-eslint/no-unsafe-unary-minus",
      "- no-throw-literal",
      "@typescript-eslint/only-throw-error",
      "- prefer-promise-reject-errors",
      "@typescript-eslint/prefer-promise-reject-errors",
      "- require-await",
      "@typescript-eslint/require-await",
      "@typescript-eslint/restrict-plus-operands",
      "@typescript-eslint/restrict-template-expressions",
      "@typescript-eslint/unbound-method",
      "- only-throw-error",
      "- prefer-destructuring",
      "@typescript-eslint/consistent-return",
      "@typescript-eslint/consistent-type-exports",
      "@typescript-eslint/no-unnecessary-qualifier",
      "@typescript-eslint/no-unnecessary-type-conversion",
      "@typescript-eslint/prefer-readonly",
      "@typescript-eslint/promise-function-async",
      "@typescript-eslint/require-array-sort-compare",
      "@typescript-eslint/return-await",
      "@typescript-eslint/no-confusing-void-expression",
      "@typescript-eslint/no-deprecated",
      "@typescript-eslint/no-meaningless-void-operator",
      "@typescript-eslint/no-misused-spread",
      "@typescript-eslint/no-mixed-enums",
      "@typescript-eslint/no-unnecessary-boolean-literal-compare",
      "@typescript-eslint/no-unnecessary-condition",
      "@typescript-eslint/no-unnecessary-template-expression",
      "@typescript-eslint/no-unnecessary-type-arguments",
      "@typescript-eslint/no-unnecessary-type-parameters",
      "@typescript-eslint/no-useless-default-assignment",
      "@typescript-eslint/prefer-reduce-type-parameter",
      "@typescript-eslint/prefer-return-this-type",
      "@typescript-eslint/related-getter-setter-pairs",
      "- no-return-await",
      "@typescript-eslint/use-unknown-in-catch-callback-variable",
      "@typescript-eslint/consistent-type-definitions",
      "@typescript-eslint/prefer-destructuring",
      "@typescript-eslint/strict-boolean-expressions",
      "@typescript-eslint/switch-exhaustiveness-check",
      "- dot-notation",
      "@typescript-eslint/dot-notation",
      "@typescript-eslint/non-nullable-type-assertion-style",
      "@typescript-eslint/prefer-find",
      "@typescript-eslint/prefer-includes",
      "@typescript-eslint/prefer-nullish-coalescing",
      "@typescript-eslint/prefer-optional-chain",
      "@typescript-eslint/prefer-regexp-exec",
      "@typescript-eslint/prefer-string-starts-ends-with",
    ],
  },
  {
    "files": [
      "**/?(.)*.d.?([cm])ts",
    ],
    "name": "moso/typescript/dts-overrides",
    "rules": [
      "- @eslint-community/eslint-comments/no-unlimited-disable",
      "- @stylistic/quote-props",
      "- no-duplicate-imports",
      "- no-restricted-syntax",
      "- unused-imports/no-unused-vars",
    ],
  },
  {
    "files": [
      [
        "**/__tests__/**/?(.)*.?([cm])[jt]s?(x)",
        "**/?(.)*.spec.?([cm])[jt]s?(x)",
        "**/?(.)*.test.?([cm])[jt]s?(x)",
        "**/?(.)*.bench.?([cm])[jt]s?(x)",
        "**/?(.)*.benchmark.?([cm])[jt]s?(x)",
      ],
    ],
    "name": "moso/typescript/test-overrides",
    "rules": [
      "- @typescript-eslint/consistent-type-definitions",
      "- @typescript-eslint/no-unused-expressions",
      "- @typescript-eslint/triple-slash-reference",
      "- no-unused-expressions",
    ],
  },
  {
    "files": [
      "**/*.?([cm])js",
      "**/*.?([cm])jsx",
    ],
    "name": "moso/typescript/javascript-overrides",
    "rules": [
      "- @typescript-eslint/ban-ts-comment",
      "- @typescript-eslint/no-require-imports",
    ],
  },
  {
    "languageOptions": {},
    "name": "moso/vue/setup",
    "plugins": [
      "vue",
    ],
  },
  {
    "files": [
      "**/*.vue",
    ],
    "languageOptions": {
      "parser": "vue-eslint-parser",
      "parserOptions": {
        "ecmaFeatures": {
          "jsx": true,
        },
        "extraFileExtensions": [
          ".vue",
        ],
        "sourceType": "module",
      },
    },
    "name": "moso/vue/rules",
    "processor": "merged-processor:eslint-plugin-vue+eslint-processor-vue-blocks",
    "rules": [
      "vue/comment-directive",
      "vue/jsx-uses-vars",
      "vue/multi-word-component-names",
      "vue/no-arrow-functions-in-watch",
      "vue/no-async-in-computed-properties",
      "vue/no-child-content",
      "vue/no-computed-properties-in-data",
      "vue/no-deprecated-data-object-declaration",
      "vue/no-deprecated-delete-set",
      "vue/no-deprecated-destroyed-lifecycle",
      "vue/no-deprecated-dollar-listeners-api",
      "vue/no-deprecated-dollar-scopedslots-api",
      "vue/no-deprecated-events-api",
      "vue/no-deprecated-filter",
      "vue/no-deprecated-functional-template",
      "vue/no-deprecated-html-element-is",
      "vue/no-deprecated-inline-template",
      "vue/no-deprecated-model-definition",
      "vue/no-deprecated-props-default-this",
      "vue/no-deprecated-router-link-tag-prop",
      "vue/no-deprecated-scope-attribute",
      "vue/no-deprecated-slot-attribute",
      "vue/no-deprecated-slot-scope-attribute",
      "vue/no-deprecated-v-bind-sync",
      "vue/no-deprecated-v-is",
      "vue/no-deprecated-v-on-native-modifier",
      "vue/no-deprecated-v-on-number-modifiers",
      "vue/no-deprecated-vue-config-keycodes",
      "vue/no-dupe-keys",
      "vue/no-dupe-v-else-if",
      "vue/no-duplicate-attributes",
      "vue/no-export-in-script-setup",
      "vue/no-expose-after-await",
      "vue/no-lifecycle-after-await",
      "vue/no-mutating-props",
      "vue/no-parsing-error",
      "vue/no-ref-as-operand",
      "vue/no-reserved-component-names",
      "vue/no-reserved-keys",
      "vue/no-reserved-props",
      "vue/no-shared-component-data",
      "vue/no-side-effects-in-computed-properties",
      "vue/no-template-key",
      "vue/no-textarea-mustache",
      "vue/no-unused-components",
      "vue/no-unused-vars",
      "vue/no-use-computed-property-like-method",
      "vue/no-use-v-if-with-v-for",
      "vue/no-useless-template-attributes",
      "vue/no-v-for-template-key-on-child",
      "- vue/no-v-text-v-html-on-component",
      "vue/no-watch-after-await",
      "vue/prefer-import-from-vue",
      "vue/require-component-is",
      "vue/require-prop-type-constructor",
      "vue/require-render-return",
      "vue/require-slots-as-functions",
      "vue/require-toggle-inside-transition",
      "vue/require-v-for-key",
      "vue/require-valid-default-prop",
      "vue/return-in-computed-property",
      "vue/return-in-emits-validator",
      "vue/use-v-on-exact",
      "vue/valid-attribute-name",
      "vue/valid-define-emits",
      "vue/valid-define-options",
      "vue/valid-define-props",
      "vue/valid-next-tick",
      "vue/valid-template-root",
      "vue/valid-v-bind",
      "vue/valid-v-cloak",
      "vue/valid-v-else-if",
      "vue/valid-v-else",
      "vue/valid-v-for",
      "vue/valid-v-html",
      "vue/valid-v-if",
      "vue/valid-v-is",
      "vue/valid-v-memo",
      "vue/valid-v-model",
      "vue/valid-v-on",
      "vue/valid-v-once",
      "vue/valid-v-pre",
      "vue/valid-v-show",
      "vue/valid-v-slot",
      "vue/valid-v-text",
      "vue/attribute-hyphenation",
      "vue/component-definition-name-casing",
      "vue/first-attribute-linebreak",
      "vue/html-closing-bracket-newline",
      "vue/html-closing-bracket-spacing",
      "vue/html-end-tags",
      "vue/html-indent",
      "vue/html-quotes",
      "- vue/html-self-closing",
      "vue/max-attributes-per-line",
      "vue/multiline-html-element-content-newline",
      "vue/mustache-interpolation-spacing",
      "vue/no-multi-spaces",
      "vue/no-spaces-around-equal-signs-in-attribute",
      "vue/no-template-shadow",
      "- vue/one-component-per-file",
      "vue/prop-name-casing",
      "- vue/require-default-prop",
      "vue/require-explicit-emits",
      "vue/require-prop-types",
      "vue/singleline-html-element-content-newline",
      "vue/v-bind-style",
      "vue/v-on-event-hyphenation",
      "vue/v-on-style",
      "vue/v-slot-style",
      "vue/attributes-order",
      "vue/block-order",
      "vue/no-lone-template",
      "vue/no-multiple-slot-args",
      "vue/no-required-prop-with-default",
      "vue/no-v-html",
      "vue/order-in-components",
      "vue/this-in-template",
      "- node/prefer-global/process",
      "vue/component-name-in-template-casing",
      "vue/component-options-name-casing",
      "vue/custom-event-name-casing",
      "vue/define-macros-order",
      "vue/dot-location",
      "vue/dot-notation",
      "vue/eqeqeq",
      "vue/no-empty-pattern",
      "vue/no-irregular-whitespace",
      "vue/no-loss-of-precision",
      "vue/no-restricted-syntax",
      "vue/no-restricted-v-bind",
      "vue/no-sparse-arrays",
      "vue/no-unused-refs",
      "vue/no-useless-v-bind",
      "vue/object-shorthand",
      "vue/prefer-separate-static-class",
      "vue/prefer-template",
      "vue/space-infix-ops",
      "vue/space-unary-ops",
      "vue/array-bracket-spacing",
      "vue/arrow-spacing",
      "vue/block-spacing",
      "vue/block-tag-newline",
      "vue/brace-style",
      "vue/comma-dangle",
      "vue/comma-spacing",
      "vue/comma-style",
      "vue/html-comment-content-spacing",
      "vue/key-spacing",
      "vue/keyword-spacing",
      "vue/object-curly-spacing",
      "vue/object-property-newline",
      "vue/operator-linebreak",
      "vue/padding-line-between-blocks",
      "vue/quote-props",
      "vue/space-in-parens",
      "vue/template-curly-spacing",
      "- no-undef",
      "- no-dupe-class-members",
      "- no-redeclare",
      "- no-unused-vars",
      "- no-array-constructor",
      "@typescript-eslint/no-array-constructor",
      "- no-unused-expressions",
      "@typescript-eslint/no-unused-expressions",
      "- no-useless-constructor",
      "@typescript-eslint/no-useless-constructor",
      "- camelcase",
      "- vue/camelcase",
      "@typescript-eslint/naming-convention",
      "- no-use-before-define",
      "@typescript-eslint/no-use-before-define",
    ],
  },
  {
    "files": [
      "**/*.?([cm])ts",
      "**/*.?([cm])tsx",
      "**/*.vue",
    ],
    "name": "moso/vue/rules-type-aware",
    "rules": [
      "- no-implied-eval",
      "@typescript-eslint/no-implied-eval",
      "- no-unused-vars",
      "- vue/no-unused-vars",
      "@typescript-eslint/no-unused-vars",
      "- prefer-promise-reject-errors",
      "@typescript-eslint/prefer-promise-reject-errors",
    ],
  },
  {
    "name": "moso/vue/a11y",
    "plugins": [
      "vue-a11y",
    ],
    "rules": [
      "vuejs-accessibility/alt-text",
      "vuejs-accessibility/anchor-has-content",
      "vuejs-accessibility/aria-props",
      "vuejs-accessibility/aria-role",
      "vuejs-accessibility/aria-unsupported-elements",
      "vuejs-accessibility/click-events-have-key-events",
      "vuejs-accessibility/form-control-has-label",
      "vuejs-accessibility/heading-has-content",
      "vuejs-accessibility/iframe-has-title",
      "vuejs-accessibility/interactive-supports-focus",
      "vuejs-accessibility/label-has-for",
      "vuejs-accessibility/media-has-caption",
      "vuejs-accessibility/mouse-events-have-key-events",
      "vuejs-accessibility/no-access-key",
      "vuejs-accessibility/no-autofocus",
      "vuejs-accessibility/no-distracting-elements",
      "vuejs-accessibility/no-redundant-roles",
      "vuejs-accessibility/no-static-element-interactions",
      "vuejs-accessibility/role-has-required-aria-props",
      "vuejs-accessibility/tabindex-no-positive",
    ],
  },
  {
    "name": "moso/yaml/setup",
    "plugins": [
      "yml",
    ],
  },
  {
    "files": [
      "**/*.y?(a)ml",
    ],
    "language": "yml/yaml",
    "languageOptions": {
      "parser": "yaml-eslint-parser",
    },
    "name": "moso/yaml/rules",
    "rules": [
      "- @stylistic/spaced-comment",
      "yml/block-mapping",
      "yml/block-sequence",
      "yml/no-empty-key",
      "yml/no-empty-sequence-entry",
      "yml/no-irregular-whitespace",
      "yml/plain-scalar",
      "yml/vue-custom-block/no-parsing-error",
      "yml/block-mapping-question-indicator-newline",
      "yml/block-sequence-hyphen-indicator-newline",
      "yml/flow-mapping-curly-newline",
      "yml/flow-mapping-curly-spacing",
      "yml/flow-sequence-bracket-newline",
      "yml/flow-sequence-bracket-spacing",
      "yml/indent",
      "yml/key-spacing",
      "yml/no-tab-indent",
      "yml/spaced-comment",
      "yml/quotes",
    ],
  },
  {
    "files": [
      "**/bin/**/*",
      "**/bin.?([cm])[jt]s?(x)",
    ],
    "name": "moso/disables/bin",
    "rules": [
      "- @moso/no-import-from-dist",
      "- @moso/no-import-node-modules-by-path",
    ],
  },
  {
    "files": [
      "**/*.js",
      "**/*.cjs",
    ],
    "name": "moso/disables/cjs",
    "rules": [
      "- @typescript-eslint/no-require-imports",
    ],
  },
  {
    "files": [
      "**/cli/**/*.?([cm])[jt]s?(x)",
      "**/cli.?([cm])[jt]s?(x)",
    ],
    "name": "moso/disables/cli",
    "rules": [
      "- @moso/no-top-level-await",
      "- no-console",
    ],
  },
  {
    "files": [
      "**/*.config.?([cm])[jt]s?(x)",
      "**/*.config.*.?([cm])[jt]s?(x)",
    ],
    "name": "moso/disables/config-files",
    "rules": [
      "- @moso/no-top-level-await",
      "- @typescript-eslint/explicit-function-return-type",
      "- no-console",
    ],
  },
  {
    "files": [
      "**/*.d.?([cm])ts",
    ],
    "name": "moso/disables/dts",
    "rules": [
      "- @eslint-community/eslint-comments/no-unlimited-disable",
      "- import-lite/no-duplicates",
      "- unused-imports/no-unused-vars",
      "- no-restricted-syntax",
    ],
  },
  {
    "files": [
      "**/scripts/**/*.?([cm])[jt]s?(x)",
    ],
    "name": "moso/disables/scripts",
    "rules": [
      "- @moso/no-top-level-await",
      "- @typescript-eslint/explicit-function-return-type",
      "- functional/no-conditional-statements",
      "- functional/no-expression-statements",
      "- functional/no-loop-statements",
      "- functional/no-return-void",
      "- functional/no-throw-statements",
      "- node/no-sync",
      "- node/no-unpublished-import",
      "- no-console",
    ],
  },
  {
    "files": [
      "typings/**/?(.)*.?([cm])ts",
    ],
    "name": "moso/disables/typings",
    "rules": [
      "- functional/functional-parameters",
      "- functional/immutable-data",
      "- functional/no-classes",
      "- functional/no-class-inheritance",
      "- functional/no-conditional-statements",
      "- functional/no-expression-statements",
      "- functional/no-let",
      "- functional/no-loop-statements",
      "- functional/no-mixed-types",
      "- functional/no-promise-reject",
      "- functional/no-return-void",
      "- functional/no-this-expressions",
      "- functional/no-throw-statements",
      "- functional/no-try-statements",
      "- functional/prefer-immutable-types",
      "- functional/prefer-property-signatures",
      "- functional/prefer-readonly-type",
      "- functional/prefer-tacit",
      "- functional/readonly-type",
      "- functional/type-declaration-immutability",
      "- jsdoc/check-examples",
      "- jsdoc/check-indentation",
      "- jsdoc/check-line-alignment",
      "- jsdoc/check-param-names",
      "- jsdoc/check-property-names",
      "- jsdoc/check-types",
      "- jsdoc/check-values",
      "- jsdoc/no-bad-blocks",
      "- jsdoc/no-defaults",
      "- jsdoc/require-asterisk-prefix",
      "- jsdoc/require-description",
      "- jsdoc/require-description-complete-sentence",
      "- jsdoc/require-hyphen-before-param-description",
      "- jsdoc/require-jsdoc",
      "- jsdoc/require-param-name",
      "- jsdoc/require-param",
      "- jsdoc/require-property-name",
      "- jsdoc/require-property",
      "- jsdoc/require-returns-check",
      "- jsdoc/require-returns",
      "- jsdoc/require-throws",
      "- jsdoc/require-yields-check",
      "- jsdoc/tag-lines",
      "- jsdoc/check-access",
      "- jsdoc/empty-tags",
      "- jsdoc/implements-on-classes",
      "- jsdoc/no-multi-asterisks",
      "- jsdoc/require-property-description",
      "- jsdoc/require-returns-description",
      "- jsdoc/check-alignment",
      "- jsdoc/multiline-blocks",
      "- @typescript-eslint/consistent-type-definitions",
      "- @typescript-eslint/no-empty-object-type",
      "- @typescript-eslint/no-explicit-any",
      "- @typescript-eslint/no-unused-vars",
    ],
  },
]