[
  {
    "languageOptions": {
      "ecmaVersion": "latest",
      "parserOptions": {
        "ecmaFeatures": {
          "jsx": true,
        },
        "ecmaVersion": "latest",
        "sourceType": "module",
      },
      "sourceType": "module",
    },
    "linterOptions": {
      "reportUnusedDisableDirectives": true,
    },
    "name": "moso/javascript",
    "plugins": [
      "unused-imports",
    ],
    "rules": [
      "constructor-super",
      "for-direction",
      "getter-return",
      "no-async-promise-executor",
      "no-case-declarations",
      "no-class-assign",
      "no-compare-neg-zero",
      "no-cond-assign",
      "no-const-assign",
      "no-constant-binary-expression",
      "no-constant-condition",
      "no-control-regex",
      "no-debugger",
      "no-delete-var",
      "no-dupe-args",
      "no-dupe-class-members",
      "no-dupe-else-if",
      "no-dupe-keys",
      "no-duplicate-case",
      "no-empty",
      "no-empty-character-class",
      "no-empty-pattern",
      "no-empty-static-block",
      "no-ex-assign",
      "no-extra-boolean-cast",
      "no-fallthrough",
      "no-func-assign",
      "no-global-assign",
      "no-import-assign",
      "no-invalid-regexp",
      "no-irregular-whitespace",
      "no-loss-of-precision",
      "no-misleading-character-class",
      "no-new-native-nonconstructor",
      "no-nonoctal-decimal-escape",
      "no-obj-calls",
      "no-octal",
      "no-prototype-builtins",
      "no-redeclare",
      "no-regex-spaces",
      "no-self-assign",
      "no-setter-return",
      "no-shadow-restricted-names",
      "no-sparse-arrays",
      "no-this-before-super",
      "no-unassigned-vars",
      "no-undef",
      "no-unexpected-multiline",
      "no-unreachable",
      "no-unsafe-finally",
      "no-unsafe-negation",
      "no-unsafe-optional-chaining",
      "no-unused-labels",
      "no-unused-private-class-members",
      "no-unused-vars",
      "no-useless-assignment",
      "no-useless-backreference",
      "no-useless-catch",
      "no-useless-escape",
      "no-with",
      "preserve-caught-error",
      "require-yield",
      "use-isnan",
      "valid-typeof",
      "array-callback-return",
      "no-await-in-loop",
      "no-constructor-return",
      "no-duplicate-imports",
      "no-inner-declarations",
      "no-promise-executor-return",
      "no-self-compare",
      "no-template-curly-in-string",
      "no-unmodified-loop-condition",
      "no-unreachable-loop",
      "no-use-before-define",
      "require-atomic-updates",
      "accessor-pairs",
      "arrow-body-style",
      "block-scoped-var",
      "- camelcase",
      "class-methods-use-this",
      "consistent-return",
      "- consistent-this",
      "curly",
      "default-case-last",
      "dot-notation",
      "eqeqeq",
      "func-name-matching",
      "func-style",
      "grouped-accessor-pairs",
      "guard-for-in",
      "new-cap",
      "no-alert",
      "no-array-constructor",
      "no-caller",
      "no-console",
      "no-else-return",
      "no-eq-null",
      "no-eval",
      "no-extra-bind",
      "no-implied-eval",
      "no-invalid-this",
      "no-iterator",
      "no-label-var",
      "no-labels",
      "no-lone-blocks",
      "no-lonely-if",
      "no-loop-func",
      "no-multi-assign",
      "no-multi-str",
      "no-new",
      "no-new-func",
      "no-new-wrappers",
      "no-object-constructor",
      "no-octal-escape",
      "no-param-reassign",
      "no-proto",
      "- no-restricted-globals",
      "no-restricted-properties",
      "no-restricted-syntax",
      "- no-return-assign",
      "no-sequences",
      "no-throw-literal",
      "no-undef-init",
      "no-unneeded-ternary",
      "no-unused-expressions",
      "no-useless-call",
      "no-useless-computed-key",
      "no-useless-concat",
      "no-useless-constructor",
      "no-useless-rename",
      "no-var",
      "object-shorthand",
      "one-var",
      "operator-assignment",
      "prefer-arrow-callback",
      "prefer-const",
      "prefer-destructuring",
      "prefer-exponentiation-operator",
      "prefer-numeric-literals",
      "prefer-object-has-own",
      "prefer-object-spread",
      "prefer-promise-reject-errors",
      "prefer-regex-literals",
      "prefer-rest-params",
      "prefer-spread",
      "prefer-template",
      "radix",
      "require-await",
      "require-unicode-regexp",
      "strict",
      "symbol-description",
      "vars-on-top",
      "yoda",
      "unicode-bom",
      "unused-imports/no-unused-imports",
      "unused-imports/no-unused-vars",
      "max-classes-per-file",
      "sort-imports",
    ],
  },
  {
    "files": [
      "**/config*.?([cm])[jt]s?(x)",
      "**/{api,helpers,middleware,modules,pages,plugins,routes,views}/**/*.?([cm])[jt]s?(x)",
      "**/{esbuild,farm,index,next,nuxt,rolldown,rollup,rspack,vite,webpack}.?([cm])[jt]s?(x)",
      "**/*.md/**",
      "**/*.d.ts",
      "**/.prettierrc",
    ],
    "name": "moso/disables/allow-default-export",
    "rules": [
      "- import-lite/no-default-export",
    ],
  },
  {
    "files": [
      "**/bin/**/*",
      "**/bin.?([cm])[jt]s?(x)",
    ],
    "name": "moso/disables/bin",
    "rules": [
      "- @moso/no-import-from-dist",
      "- @moso/no-import-node-modules-by-path",
    ],
  },
  {
    "files": [
      "**/*.js",
      "**/*.cjs",
    ],
    "name": "moso/disables/cjs",
    "rules": [
      "- @typescript-eslint/no-require-imports",
    ],
  },
  {
    "files": [
      "**/cli/**/*.?([cm])[jt]s?(x)",
      "**/cli.?([cm])[jt]s?(x)",
    ],
    "name": "moso/disables/cli",
    "rules": [
      "- @moso/no-top-level-await",
      "- baseline-js/use-baseline",
      "- no-console",
    ],
  },
  {
    "files": [
      "**/*.?([cm])jsx",
      "**/*.?([cm])tsx",
    ],
    "name": "moso/disables/components",
    "rules": [
      "- unicorn/no-anonymous-default-export",
    ],
  },
  {
    "files": [
      "**/*.config.?([cm])[jt]s?(x)",
      "**/{esbuild,farm,index,next,nuxt,rolldown,rollup,rspack,vite,webpack}.?([cm])[jt]s?(x)",
    ],
    "name": "moso/disables/config-files",
    "rules": [
      "- @moso/no-top-level-await",
      "- @typescript-eslint/explicit-function-return-type",
      "- no-console",
    ],
  },
  {
    "files": [
      "**/*.d.?([cm])ts",
    ],
    "name": "moso/disables/dts",
    "rules": [
      "- no-restricted-syntax",
      "- @eslint-community/eslint-comments/no-unlimited-disable",
      "- import-lite/no-duplicates",
      "- unused-imports/no-unused-vars",
    ],
  },
  {
    "files": [
      "**/ISSUE_TEMPLATE/**",
    ],
    "name": "moso/disables/github",
    "rules": [
      "- unicorn/filename-case",
    ],
  },
  {
    "files": [
      "**/*.astro",
      "**/*.astro/*.ts",
      "**/?(.)*.d.?([cm])ts",
      "**/*.?([cm])jsx",
      "**/*.?([cm])ts",
      "**/*.?([cm])tsx",
      "**/*.vue",
    ],
    "name": "moso/disables/node-frameworks",
    "rules": [
      "- node/no-extraneous-import",
      "- node/no-missing-import",
      "- node/no-restricted-import",
    ],
  },
  {
    "files": [
      "**/?(.)*.d.?([cm])ts",
      "**/*.mjs",
      "**/*.?([cm])ts",
      "**/*.?([cm])tsx",
    ],
    "name": "moso/disables/node-typescript",
    "rules": [
      "- node/no-unsupported-features/es-syntax",
    ],
  },
  {
    "files": [
      "**/scripts/**/*.?([cm])[jt]s?(x)",
    ],
    "name": "moso/disables/scripts",
    "rules": [
      "- @moso/no-top-level-await",
      "- baseline-js/use-baseline",
      "- no-console",
      "- @typescript-eslint/explicit-function-return-type",
      "- functional/no-conditional-statements",
      "- functional/no-expression-statements",
      "- functional/no-loop-statements",
      "- functional/no-return-void",
      "- functional/no-throw-statements",
      "- node/no-sync",
      "- node/no-unpublished-import",
    ],
  },
  {
    "files": [
      "**/__tests__/**/?(.)*.?([cm])[jt]s?(x)",
      "**/?(.)*.spec.?([cm])[jt]s?(x)",
      "**/?(.)*.test.?([cm])[jt]s?(x)",
      "**/?(.)*.bench.?([cm])[jt]s?(x)",
      "**/?(.)*.benchmark.?([cm])[jt]s?(x)",
    ],
    "name": "moso/disables/tests",
    "rules": [
      "- @moso/no-top-level-await",
      "- baseline-js/use-baseline",
      "- e18e/prefer-static-regex",
      "- no-unused-expressions",
      "- jsdoc/require-jsdoc",
      "- node/no-sync",
      "- node/prefer-global/process",
      "- regexp/no-super-linear-backtracking",
      "- unicorn/consistent-function-scoping",
      "- unicorn/prefer-module",
      "- @typescript-eslint/consistent-type-definitions",
      "- @typescript-eslint/explicit-function-return-type",
      "- @typescript-eslint/no-unsafe-argument",
      "- @typescript-eslint/no-unsafe-assignment",
      "- @typescript-eslint/no-unsafe-call",
      "- @typescript-eslint/no-unsafe-member-access",
      "- @typescript-eslint/no-unsafe-return",
      "- @typescript-eslint/no-unused-expressions",
      "- @typescript-eslint/no-unused-vars",
      "- @typescript-eslint/strict-boolean-expressions",
    ],
  },
  {
    "files": [
      "typings/**/?(.)*.?([cm])ts",
    ],
    "name": "moso/disables/typings",
    "rules": [
      "- jsdoc/check-examples",
      "- jsdoc/check-indentation",
      "- jsdoc/check-line-alignment",
      "- jsdoc/check-param-names",
      "- jsdoc/check-property-names",
      "- jsdoc/check-types",
      "- jsdoc/check-values",
      "- jsdoc/no-bad-blocks",
      "- jsdoc/no-defaults",
      "- jsdoc/require-asterisk-prefix",
      "- jsdoc/require-description",
      "- jsdoc/require-description-complete-sentence",
      "- jsdoc/require-hyphen-before-param-description",
      "- jsdoc/require-jsdoc",
      "- jsdoc/require-param-name",
      "- jsdoc/require-param",
      "- jsdoc/require-property-name",
      "- jsdoc/require-property",
      "- jsdoc/require-returns-check",
      "- jsdoc/require-returns",
      "- jsdoc/require-throws",
      "- jsdoc/require-yields-check",
      "- jsdoc/tag-lines",
      "- jsdoc/check-access",
      "- jsdoc/empty-tags",
      "- jsdoc/implements-on-classes",
      "- jsdoc/no-multi-asterisks",
      "- jsdoc/require-property-description",
      "- jsdoc/require-returns-description",
      "- jsdoc/check-alignment",
      "- jsdoc/multiline-blocks",
      "- @typescript-eslint/consistent-type-definitions",
      "- @typescript-eslint/no-empty-object-type",
      "- @typescript-eslint/no-explicit-any",
      "- @typescript-eslint/no-unused-vars",
    ],
  },
]