[
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
      "**/*.astro",
      "**/*.vue",
    ],
    "name": "moso/eslint-comments",
    "plugins": [
      "@eslint-community/eslint-comments",
    ],
    "rules": [
      "@eslint-community/eslint-comments/disable-enable-pair",
      "@eslint-community/eslint-comments/no-aggregating-enable",
      "@eslint-community/eslint-comments/no-duplicate-disable",
      "@eslint-community/eslint-comments/no-unlimited-disable",
      "@eslint-community/eslint-comments/no-unused-enable",
    ],
  },
  {
    "ignores": [
      "**/node_modules",
      "**/dist",
      "**/lib",
      "**/package-lock.json",
      "**/yarn.lock",
      "**/pnpm-lock.yaml",
      "**/bun.lockb",
      "**/bun.lock",
      "**/output",
      "**/coverage",
      "**/temp",
      "**/.temp",
      "**/tmp",
      "**/.tmp",
      "**/.history",
      "**/.vitepress/cache",
      "**/.nuxt",
      "**/.next",
      "**/.vercel",
      "**/.changeset",
      "**/.idea",
      "**/.cache",
      "**/.output",
      "**/.vite-inspect",
      "**/.yarn",
      "**/vite.config.*.timestamp-*",
      "**/CHANGELOG*.md",
      "**/*.min.*",
      "**/LICENSE*",
      "**/__snapshots__",
      "**/auto-import?(s).ts",
      "**/auto-import?(s).d.ts",
      "**/components.ts",
      "**/components.d.ts",
      "**/typegen.ts",
      "**/typegen.d.ts",
      "**/*.?([cm])ts",
      "**/*.?([cm])tsx",
    ],
    "name": "moso/ignores/globals",
  },
  {
    "ignores": [
      "**/node_modules/",
      "**/.cache/",
      "**/.env",
      "**/.DS_Store",
      "**/.vite-ssg-dist/",
      "**/.vite-ssg-temp/",
      "**/*.log",
      "**/dist/",
      "**/dist-ssr/",
      "public/assets/fonts",
      "**/temp/",
      "**/components.d.ts",
      "**/auto-imports.d.ts",
      "**/*.local",
      "**/.idea/",
      "**/typings/",
      "src/typegen.d.ts",
      "**/.astro/",
      "**/.content-collections",
      ".phpunit.cache",
      ".phpunit.result.cache",
      "storage/*.key",
      "storage/assets",
      "storage/dropfolder",
      "vendor",
      "**/Homestead.json",
      "**/Homestead.yaml",
      "**/auth.json",
      "**/.claude/",
      "**/.cursor/",
      ".github/hooks/",
      ".github/copilot-instuctions.md",
      ".vscode/CLAUDE.md",
      ".vscode/settings.json",
      ".vscode/mcp.json",
      ".mcp.json",
      "CLAUDE.md",
      "PROJECT.md",
      "**/.eslint-config-inspector/",
      "**/coverage/",
      "**/sponsors.*",
      "**/drafts/",
    ],
    "name": "moso/ignores/gitignore",
  },
  {
    "name": "moso/imports",
    "plugins": [
      "@moso",
      "import-lite",
    ],
    "rules": [
      "@moso/no-import-duplicates",
      "@moso/no-import-from-dist",
      "@moso/no-import-node-modules-by-path",
      "import-lite/consistent-type-specifier-style",
      "import-lite/first",
      "import-lite/no-duplicates",
      "import-lite/no-mutable-exports",
      "import-lite/no-named-default",
      "import-lite/newline-after-import",
    ],
  },
  {
    "files": [
      "**/?(.)*.d.?([cm])ts",
      "**/*.?([cm])ts",
      "**/*.?([cm])tsx",
    ],
    "name": "moso/imports/typescript",
    "rules": [
      "@typescript-eslint/no-import-type-side-effects",
      "@typescript-eslint/consistent-type-imports",
    ],
  },
  {
    "languageOptions": {
      "ecmaVersion": "latest",
      "parserOptions": {
        "ecmaFeatures": {
          "jsx": true,
        },
        "ecmaVersion": "latest",
        "sourceType": "module",
      },
      "sourceType": "module",
    },
    "linterOptions": {
      "reportUnusedDisableDirectives": true,
    },
    "name": "moso/javascript",
    "plugins": [
      "@eslint/js",
      "unused-imports",
    ],
    "rules": [
      "constructor-super",
      "for-direction",
      "getter-return",
      "no-async-promise-executor",
      "no-case-declarations",
      "no-class-assign",
      "no-compare-neg-zero",
      "no-cond-assign",
      "no-const-assign",
      "no-constant-binary-expression",
      "no-constant-condition",
      "no-control-regex",
      "no-debugger",
      "no-delete-var",
      "no-dupe-args",
      "no-dupe-class-members",
      "no-dupe-else-if",
      "no-dupe-keys",
      "no-duplicate-case",
      "no-empty",
      "no-empty-character-class",
      "no-empty-pattern",
      "no-empty-static-block",
      "no-ex-assign",
      "no-extra-boolean-cast",
      "no-fallthrough",
      "no-func-assign",
      "no-global-assign",
      "no-import-assign",
      "no-invalid-regexp",
      "no-irregular-whitespace",
      "no-loss-of-precision",
      "no-misleading-character-class",
      "no-new-native-nonconstructor",
      "no-nonoctal-decimal-escape",
      "no-obj-calls",
      "no-octal",
      "no-prototype-builtins",
      "no-redeclare",
      "no-regex-spaces",
      "no-self-assign",
      "no-setter-return",
      "no-shadow-restricted-names",
      "no-sparse-arrays",
      "no-this-before-super",
      "no-unassigned-vars",
      "no-undef",
      "no-unexpected-multiline",
      "no-unreachable",
      "no-unsafe-finally",
      "no-unsafe-negation",
      "no-unsafe-optional-chaining",
      "no-unused-labels",
      "no-unused-private-class-members",
      "no-unused-vars",
      "no-useless-assignment",
      "no-useless-backreference",
      "no-useless-catch",
      "no-useless-escape",
      "no-with",
      "preserve-caught-error",
      "require-yield",
      "use-isnan",
      "valid-typeof",
      "array-callback-return",
      "no-await-in-loop",
      "no-constructor-return",
      "no-duplicate-imports",
      "no-inner-declarations",
      "no-promise-executor-return",
      "no-self-compare",
      "no-template-curly-in-string",
      "no-unmodified-loop-condition",
      "no-unreachable-loop",
      "no-use-before-define",
      "require-atomic-updates",
      "accessor-pairs",
      "arrow-body-style",
      "block-scoped-var",
      "- camelcase",
      "class-methods-use-this",
      "consistent-return",
      "- consistent-this",
      "curly",
      "default-case-last",
      "dot-notation",
      "eqeqeq",
      "func-name-matching",
      "func-style",
      "grouped-accessor-pairs",
      "guard-for-in",
      "new-cap",
      "no-alert",
      "no-array-constructor",
      "no-caller",
      "no-console",
      "no-else-return",
      "no-eq-null",
      "no-eval",
      "no-extra-bind",
      "no-implied-eval",
      "no-invalid-this",
      "no-iterator",
      "no-label-var",
      "no-labels",
      "no-lone-blocks",
      "no-lonely-if",
      "no-loop-func",
      "no-multi-assign",
      "no-multi-str",
      "no-new",
      "no-new-func",
      "no-new-wrappers",
      "no-object-constructor",
      "no-octal-escape",
      "no-param-reassign",
      "no-proto",
      "no-restricted-globals",
      "no-restricted-properties",
      "no-restricted-syntax",
      "- no-return-assign",
      "no-sequences",
      "no-throw-literal",
      "no-undef-init",
      "no-unneeded-ternary",
      "no-unused-expressions",
      "no-useless-call",
      "no-useless-computed-key",
      "no-useless-concat",
      "no-useless-constructor",
      "no-useless-rename",
      "no-var",
      "object-shorthand",
      "one-var",
      "operator-assignment",
      "prefer-arrow-callback",
      "prefer-const",
      "prefer-destructuring",
      "prefer-exponentiation-operator",
      "prefer-numeric-literals",
      "prefer-object-has-own",
      "prefer-object-spread",
      "prefer-promise-reject-errors",
      "prefer-regex-literals",
      "prefer-rest-params",
      "prefer-spread",
      "prefer-template",
      "radix",
      "require-await",
      "require-unicode-regexp",
      "strict",
      "symbol-description",
      "vars-on-top",
      "yoda",
      "unicode-bom",
      "unused-imports/no-unused-imports",
      "unused-imports/no-unused-vars",
    ],
  },
  {
    "name": "moso/javascript/opinionated",
    "plugins": [
      "@moso",
      "de-morgan",
    ],
    "rules": [
      "@moso/avoid-barrel-files",
      "@moso/no-bidi",
      "@moso/no-invisible-characters",
      "@moso/no-redundant-variable",
      "@moso/no-string-interpolation",
      "@moso/no-top-level-await",
      "@moso/no-unneeded-array-flat-map",
      "@moso/prefer-early-return",
      "@moso/prefer-fetch",
      "@moso/prefer-reduce-over-chaining",
      "de-morgan/no-negated-conjunction",
      "de-morgan/no-negated-disjunction",
    ],
  },
  {
    "languageOptions": {},
    "name": "moso/node",
    "plugins": [
      "node",
    ],
    "rules": [
      "node/no-deprecated-api",
      "node/no-exports-assign",
      "node/no-extraneous-import",
      "node/no-extraneous-require",
      "node/no-missing-import",
      "- node/no-missing-require",
      "node/no-process-exit",
      "node/no-unpublished-import",
      "node/no-unpublished-require",
      "node/no-unsupported-features/es-builtins",
      "node/no-unsupported-features/es-syntax",
      "node/no-unsupported-features/node-builtins",
      "node/process-exit-as-throw",
      "node/hashbang",
      "node/prefer-global/process",
      "node/prefer-global/text-decoder",
      "node/prefer-global/text-encoder",
      "node/prefer-global/url-search-params",
      "- node/no-top-level-await",
      "node/callback-return",
      "node/handle-callback-err",
      "node/no-callback-literal",
      "node/no-mixed-requires",
      "node/no-new-require",
      "node/no-path-concat",
      "node/no-restricted-import",
      "- node/no-restricted-require",
      "node/no-sync",
      "node/prefer-global/buffer",
      "node/prefer-global/console",
      "node/prefer-promises/dns",
      "node/prefer-promises/fs",
    ],
    "settings": {
      "node": {
        "version": "^22.22.2 || >=24",
      },
    },
  },
  {
    "files": [
      "**/?(.)*.d.?([cm])ts",
      "**/*.mjs",
      "**/*.?([cm])ts",
      "**/*.?([cm])tsx",
    ],
    "rules": [
      "- node/no-unsupported-features/es-syntax",
    ],
  },
  {
    "files": [
      "**/?(.)*.d.?([cm])ts",
      "**/*.?([cm])ts",
      "**/*.?([cm])tsx",
    ],
    "rules": [
      "- node/no-extraneous-import",
      "- node/no-missing-import",
      "- node/no-restricted-import",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
      "**/*.astro",
      "**/*.vue",
    ],
    "name": "moso/promise",
    "plugins": [
      "promise",
    ],
    "rules": [
      "promise/no-callback-in-promise",
      "promise/no-nesting",
      "promise/no-new-statics",
      "promise/no-promise-in-callback",
      "promise/no-return-in-finally",
      "promise/no-return-wrap",
      "promise/param-names",
      "promise/valid-params",
      "- promise/always-return",
      "- promise/avoid-new",
      "promise/catch-or-return",
      "- promise/no-native",
      "promise/prefer-catch",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
      "**/*.astro",
      "**/*.vue",
    ],
    "name": "moso/regexp",
    "plugins": [
      "regexp",
    ],
    "rules": [
      "- no-empty-character-class",
      "- no-invalid-regexp",
      "- no-useless-backreference",
      "no-control-regex",
      "no-misleading-character-class",
      "no-regex-spaces",
      "prefer-regex-literals",
      "regexp/confusing-quantifier",
      "regexp/control-character-escape",
      "regexp/match-any",
      "regexp/negation",
      "regexp/no-contradiction-with-assertion",
      "regexp/no-dupe-characters-character-class",
      "regexp/no-dupe-disjunctions",
      "regexp/no-empty-alternative",
      "regexp/no-empty-capturing-group",
      "regexp/no-empty-character-class",
      "regexp/no-empty-group",
      "regexp/no-empty-lookarounds-assertion",
      "regexp/no-empty-string-literal",
      "regexp/no-escape-backspace",
      "regexp/no-extra-lookaround-assertions",
      "regexp/no-invalid-regexp",
      "regexp/no-invisible-character",
      "regexp/no-lazy-ends",
      "regexp/no-legacy-features",
      "regexp/no-misleading-capturing-group",
      "regexp/no-misleading-unicode-character",
      "regexp/no-missing-g-flag",
      "regexp/no-non-standard-flag",
      "regexp/no-obscure-range",
      "regexp/no-optional-assertion",
      "regexp/no-potentially-useless-backreference",
      "regexp/no-super-linear-backtracking",
      "regexp/no-trivially-nested-assertion",
      "regexp/no-trivially-nested-quantifier",
      "regexp/no-unused-capturing-group",
      "regexp/no-useless-assertions",
      "regexp/no-useless-backreference",
      "regexp/no-useless-character-class",
      "regexp/no-useless-dollar-replacements",
      "regexp/no-useless-escape",
      "regexp/no-useless-flag",
      "regexp/no-useless-lazy",
      "regexp/no-useless-non-capturing-group",
      "regexp/no-useless-quantifier",
      "regexp/no-useless-range",
      "regexp/no-useless-set-operand",
      "regexp/no-useless-string-literal",
      "regexp/no-useless-two-nums-quantifier",
      "regexp/no-zero-quantifier",
      "regexp/optimal-lookaround-quantifier",
      "regexp/optimal-quantifier-concatenation",
      "regexp/prefer-character-class",
      "regexp/prefer-d",
      "regexp/prefer-plus-quantifier",
      "regexp/prefer-predefined-assertion",
      "regexp/prefer-question-quantifier",
      "regexp/prefer-range",
      "regexp/prefer-set-operation",
      "regexp/prefer-star-quantifier",
      "regexp/prefer-unicode-codepoint-escapes",
      "regexp/prefer-w",
      "regexp/simplify-set-operations",
      "regexp/sort-flags",
      "- regexp/strict",
      "regexp/use-ignore-case",
      "unicorn/better-regex",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
      "**/*.astro",
      "**/*.vue",
    ],
    "name": "moso/unicorn",
    "plugins": [
      "unicorn",
    ],
    "rules": [
      "unicorn/better-regex",
      "unicorn/catch-error-name",
      "unicorn/consistent-empty-array-spread",
      "unicorn/consistent-function-scoping",
      "unicorn/custom-error-definition",
      "unicorn/error-message",
      "unicorn/escape-case",
      "unicorn/new-for-builtins",
      "unicorn/no-anonymous-default-export",
      "unicorn/no-array-method-this-argument",
      "unicorn/no-await-expression-member",
      "unicorn/no-await-in-promise-methods",
      "unicorn/no-console-spaces",
      "unicorn/no-document-cookie",
      "unicorn/no-for-loop",
      "unicorn/no-hex-escape",
      "unicorn/no-instanceof-builtins",
      "unicorn/no-invalid-fetch-options",
      "unicorn/no-invalid-remove-event-listener",
      "unicorn/no-negated-condition",
      "unicorn/no-negation-in-equality-check",
      "unicorn/no-new-array",
      "unicorn/no-new-buffer",
      "unicorn/no-object-as-default-parameter",
      "unicorn/no-single-promise-in-promise-methods",
      "unicorn/no-static-only-class",
      "unicorn/no-thenable",
      "unicorn/no-this-assignment",
      "unicorn/no-typeof-undefined",
      "unicorn/no-unnecessary-array-flat-depth",
      "unicorn/no-unnecessary-await",
      "unicorn/no-unnecessary-polyfills",
      "unicorn/no-unreadable-array-destructuring",
      "unicorn/no-unreadable-iife",
      "unicorn/no-useless-fallback-in-spread",
      "unicorn/no-useless-length-check",
      "unicorn/no-useless-promise-resolve-reject",
      "unicorn/no-useless-switch-case",
      "unicorn/no-zero-fractions",
      "unicorn/number-literal-case",
      "unicorn/numeric-separators-style",
      "unicorn/prefer-add-event-listener",
      "unicorn/prefer-array-find",
      "unicorn/prefer-array-flat",
      "unicorn/prefer-array-index-of",
      "unicorn/prefer-array-some",
      "unicorn/prefer-at",
      "unicorn/prefer-blob-reading-methods",
      "unicorn/prefer-date-now",
      "unicorn/prefer-default-parameters",
      "unicorn/prefer-dom-node-append",
      "unicorn/prefer-dom-node-dataset",
      "unicorn/prefer-dom-node-remove",
      "unicorn/prefer-dom-node-text-content",
      "unicorn/prefer-event-target",
      "unicorn/prefer-export-from",
      "unicorn/prefer-import-meta-properties",
      "unicorn/prefer-includes",
      "unicorn/prefer-keyboard-event-key",
      "unicorn/prefer-logical-operator-over-ternary",
      "unicorn/prefer-modern-dom-apis",
      "unicorn/prefer-modern-math-apis",
      "unicorn/prefer-module",
      "unicorn/prefer-native-coercion-functions",
      "unicorn/prefer-node-protocol",
      "unicorn/prefer-number-properties",
      "unicorn/prefer-object-from-entries",
      "unicorn/prefer-optional-catch-binding",
      "unicorn/prefer-query-selector",
      "unicorn/prefer-reflect-apply",
      "unicorn/prefer-regexp-test",
      "unicorn/prefer-single-call",
      "unicorn/prefer-spread",
      "unicorn/prefer-string-replace-all",
      "unicorn/prefer-string-slice",
      "unicorn/prefer-string-starts-ends-with",
      "unicorn/prefer-switch",
      "unicorn/prefer-ternary",
      "- unicorn/prefer-top-level-await",
      "unicorn/prefer-type-error",
      "unicorn/require-array-join-separator",
      "unicorn/require-number-to-fixed-digits-argument",
      "unicorn/switch-case-braces",
      "unicorn/throw-new-error",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
      "**/*.astro",
      "**/*.vue",
    ],
    "name": "moso/e18e/rules",
    "plugins": [
      "e18e",
    ],
    "rules": [
      "e18e/prefer-array-at",
      "e18e/prefer-array-fill",
      "e18e/prefer-includes",
      "e18e/prefer-array-to-reversed",
      "e18e/prefer-array-to-sorted",
      "e18e/prefer-array-to-spliced",
      "e18e/prefer-nullish-coalescing",
      "e18e/prefer-object-has-own",
      "e18e/prefer-spread-syntax",
      "e18e/prefer-url-canparse",
      "e18e/prefer-array-from-map",
      "e18e/prefer-timer-args",
      "e18e/prefer-date-now",
      "e18e/prefer-regex-test",
      "e18e/prefer-array-some",
      "e18e/prefer-static-regex",
      "e18e/prefer-string-fromcharcode",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
      "**/*.astro",
      "**/*.vue",
    ],
    "name": "moso/e18e/library-disables",
    "rules": [
      "- e18e/prefer-static-regex",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
      "**/*.astro",
      "**/*.vue",
    ],
    "name": "moso/functional",
    "plugins": [
      "functional",
    ],
    "rules": [
      "functional/functional-parameters",
      "functional/immutable-data",
      "- functional/no-classes",
      "functional/no-class-inheritance",
      "- functional/no-conditional-statements",
      "- functional/no-expression-statements",
      "functional/no-let",
      "functional/no-loop-statements",
      "functional/no-mixed-types",
      "- functional/no-promise-reject",
      "- functional/no-return-void",
      "- functional/no-this-expressions",
      "functional/no-throw-statements",
      "- functional/no-try-statements",
      "- functional/prefer-immutable-types",
      "functional/prefer-property-signatures",
      "- functional/prefer-readonly-type",
      "functional/prefer-tacit",
      "functional/readonly-type",
      "- functional/type-declaration-immutability",
      "- @typescript-eslint/prefer-readonly-parameter-types",
    ],
    "settings": {
      "immutability": {
        "overrides": [
          {
            "to": "ReadonlyShallow",
            "type": "^Readonly<.+>$",
          },
          {
            "to": "ReadonlyDeep",
            "type": "^ReadonlyDeep<.+>$",
          },
          {
            "to": "Immutable",
            "type": "^Immutable<.+>$",
          },
        ],
      },
    },
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
      "**/*.astro",
      "**/*.vue",
    ],
    "name": "moso/functional/disable-type-aware",
    "rules": [
      "- functional/functional-parameters",
      "- functional/immutable-data",
      "- functional/no-conditional-statements",
      "- functional/no-expression-statements",
      "- functional/no-mixed-types",
      "- functional/no-return-void",
      "- functional/no-throw-statements",
      "- functional/prefer-immutable-types",
      "- functional/prefer-property-signatures",
      "- functional/prefer-readonly-type",
      "- functional/prefer-tacit",
      "- functional/readonly-type",
      "- functional/type-declaration-immutability",
      "functional/no-let",
    ],
  },
  {
    "files": [
      "**/*.?([cm])jsx",
      "**/*.?([cm])tsx",
    ],
    "languageOptions": {
      "parserOptions": {
        "ecmaFeatures": {
          "jsx": true,
        },
      },
    },
    "name": "moso/jsx/setup",
  },
  {
    "name": "moso/jsx/rules",
    "rules": [
      "@stylistic/jsx-curly-spacing",
      "- @stylistic/jsx-one-expression-per-line",
    ],
  },
  {
    "name": "moso/perfectionist",
    "plugins": [
      "perfectionist",
    ],
    "rules": [
      "perfectionist/sort-array-includes",
      "perfectionist/sort-classes",
      "perfectionist/sort-decorators",
      "perfectionist/sort-enums",
      "perfectionist/sort-export-attributes",
      "perfectionist/sort-exports",
      "perfectionist/sort-heritage-clauses",
      "perfectionist/sort-import-attributes",
      "perfectionist/sort-imports",
      "perfectionist/sort-interfaces",
      "perfectionist/sort-intersection-types",
      "perfectionist/sort-jsx-props",
      "perfectionist/sort-maps",
      "perfectionist/sort-modules",
      "perfectionist/sort-named-exports",
      "perfectionist/sort-named-imports",
      "perfectionist/sort-object-types",
      "perfectionist/sort-objects",
      "perfectionist/sort-sets",
      "perfectionist/sort-switch-case",
      "perfectionist/sort-union-types",
      "perfectionist/sort-variable-declarations",
    ],
  },
  {
    "name": "moso/stylistic",
    "plugins": [
      "@stylistic",
    ],
    "rules": [
      "@stylistic/array-bracket-spacing",
      "@stylistic/arrow-parens",
      "@stylistic/arrow-spacing",
      "@stylistic/block-spacing",
      "@stylistic/brace-style",
      "@stylistic/comma-dangle",
      "@stylistic/comma-spacing",
      "@stylistic/comma-style",
      "@stylistic/computed-property-spacing",
      "@stylistic/dot-location",
      "@stylistic/eol-last",
      "@stylistic/generator-star-spacing",
      "- @stylistic/indent",
      "@stylistic/indent-binary-ops",
      "@stylistic/key-spacing",
      "@stylistic/keyword-spacing",
      "@stylistic/lines-between-class-members",
      "@stylistic/max-statements-per-line",
      "@stylistic/member-delimiter-style",
      "@stylistic/multiline-ternary",
      "@stylistic/new-parens",
      "- @stylistic/no-extra-parens",
      "@stylistic/no-floating-decimal",
      "@stylistic/no-mixed-operators",
      "@stylistic/no-mixed-spaces-and-tabs",
      "@stylistic/no-multi-spaces",
      "@stylistic/no-multiple-empty-lines",
      "@stylistic/no-tabs",
      "@stylistic/no-trailing-spaces",
      "@stylistic/no-whitespace-before-property",
      "@stylistic/object-curly-spacing",
      "@stylistic/operator-linebreak",
      "@stylistic/padded-blocks",
      "@stylistic/quote-props",
      "@stylistic/quotes",
      "@stylistic/rest-spread-spacing",
      "@stylistic/semi",
      "@stylistic/semi-spacing",
      "@stylistic/space-before-blocks",
      "@stylistic/space-before-function-paren",
      "@stylistic/space-in-parens",
      "@stylistic/space-infix-ops",
      "@stylistic/space-unary-ops",
      "@stylistic/spaced-comment",
      "@stylistic/template-curly-spacing",
      "@stylistic/template-tag-spacing",
      "@stylistic/type-annotation-spacing",
      "@stylistic/type-generic-spacing",
      "@stylistic/type-named-tuple-spacing",
      "@stylistic/wrap-iife",
      "@stylistic/yield-star-spacing",
      "@stylistic/jsx-closing-bracket-location",
      "@stylistic/jsx-closing-tag-location",
      "@stylistic/jsx-curly-brace-presence",
      "@stylistic/jsx-curly-newline",
      "@stylistic/jsx-curly-spacing",
      "@stylistic/jsx-equals-spacing",
      "@stylistic/jsx-first-prop-new-line",
      "@stylistic/jsx-function-call-newline",
      "@stylistic/jsx-indent-props",
      "@stylistic/jsx-max-props-per-line",
      "@stylistic/jsx-one-expression-per-line",
      "@stylistic/jsx-quotes",
      "@stylistic/jsx-tag-spacing",
      "@stylistic/jsx-wrap-multilines",
      "@stylistic/array-element-newline",
      "@stylistic/function-call-argument-newline",
      "@stylistic/function-paren-newline",
      "@stylistic/lines-around-comment",
      "@stylistic/no-confusing-arrow",
      "@stylistic/object-curly-newline",
      "@stylistic/object-property-newline",
      "@stylistic/one-var-declaration-per-line",
      "@stylistic/wrap-regex",
    ],
  },
  {
    "languageOptions": {},
    "name": "moso/test/setup",
    "plugins": [
      "no-only-tests",
      "vitest",
    ],
    "settings": {
      "vitest": {
        "typecheck": true,
      },
    },
  },
  {
    "files": [
      "**/__tests__/**/?(.)*.?([cm])[jt]s?(x)",
      "**/?(.)*.spec.?([cm])[jt]s?(x)",
      "**/?(.)*.test.?([cm])[jt]s?(x)",
      "**/?(.)*.bench.?([cm])[jt]s?(x)",
      "**/?(.)*.benchmark.?([cm])[jt]s?(x)",
    ],
    "name": "moso/test/rules",
    "rules": [
      "- functional/functional-parameters",
      "- functional/immutable-data",
      "- functional/no-classes",
      "- functional/no-class-inheritance",
      "- functional/no-conditional-statements",
      "- functional/no-expression-statements",
      "- functional/no-let",
      "- functional/no-loop-statements",
      "- functional/no-mixed-types",
      "- functional/no-promise-reject",
      "- functional/no-return-void",
      "- functional/no-this-expressions",
      "- functional/no-throw-statements",
      "- functional/no-try-statements",
      "- functional/prefer-immutable-types",
      "- functional/prefer-property-signatures",
      "- functional/prefer-readonly-type",
      "- functional/prefer-tacit",
      "- functional/readonly-type",
      "- functional/type-declaration-immutability",
      "- @moso/no-top-level-await",
      "- jsdoc/require-jsdoc",
      "- node/no-sync",
      "- node/prefer-global/process",
      "- regexp/no-super-linear-backtracking",
      "- unicorn/consistent-function-scoping",
      "- unicorn/prefer-module",
      "- @typescript-eslint/consistent-type-definitions",
      "- @typescript-eslint/no-unsafe-argument",
      "- @typescript-eslint/no-unsafe-assignment",
      "- @typescript-eslint/no-unsafe-call",
      "- @typescript-eslint/no-unsafe-member-access",
      "- @typescript-eslint/no-unsafe-return",
      "- @typescript-eslint/no-unused-expressions",
      "- @typescript-eslint/no-unused-vars",
      "- @typescript-eslint/strict-boolean-expressions",
      "no-only-tests/no-only-tests",
      "vitest/expect-expect",
      "vitest/no-commented-out-tests",
      "vitest/no-conditional-expect",
      "vitest/no-disabled-tests",
      "vitest/no-focused-tests",
      "vitest/no-identical-title",
      "vitest/no-import-node-test",
      "vitest/no-interpolation-in-snapshots",
      "vitest/no-mocks-import",
      "vitest/no-standalone-expect",
      "vitest/no-unneeded-async-expect-function",
      "vitest/prefer-called-exactly-once-with",
      "vitest/require-local-test-context-for-concurrent-snapshots",
      "vitest/valid-describe-callback",
      "- vitest/valid-expect",
      "vitest/valid-expect-in-promise",
      "- vitest/valid-title",
      "vitest/consistent-test-it",
      "vitest/prefer-hooks-in-order",
      "vitest/prefer-lowercase-title",
    ],
  },
  {
    "name": "moso/toml/setup",
    "plugins": [
      "toml",
    ],
  },
  {
    "files": [
      "**/*.toml",
    ],
    "languageOptions": {
      "parser": "toml-eslint-parser",
    },
    "name": "moso/toml/rules",
    "rules": [
      "- @stylistic/spaced-comment",
      "toml/comma-style",
      "toml/keys-order",
      "toml/no-space-dots",
      "toml/no-unreadable-number-separator",
      "toml/precision-of-fractional-seconds",
      "toml/precision-of-integer",
      "toml/tables-order",
      "toml/vue-custom-block/no-parsing-error",
      "toml/array-bracket-newline",
      "toml/array-bracket-spacing",
      "toml/array-element-newline",
      "toml/indent",
      "toml/inline-table-curly-spacing",
      "toml/key-spacing",
      "toml/padding-line-between-pairs",
      "toml/padding-line-between-tables",
      "toml/quoted-keys",
      "toml/spaced-comment",
      "toml/table-bracket-spacing",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
    ],
    "languageOptions": {
      "parser": "typescript-eslint/parser",
      "parserOptions": {
        "ecmaFeatures": {
          "jsx": true,
        },
        "ecmaVersion": "latest",
        "extraFileExtensions": [],
        "jsxPragma": undefined,
        "sourceType": "module",
        "warnOnUnsupportedTypeScriptVersion": true,
      },
    },
    "name": "moso/typescript/setup",
    "plugins": [
      "@typescript-eslint",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
    ],
    "name": "moso/typescript/rules",
    "rules": [
      "- constructor-super",
      "- getter-return",
      "- no-class-assign",
      "- no-const-assign",
      "- no-dupe-args",
      "- no-dupe-class-members",
      "- no-dupe-keys",
      "- no-func-assign",
      "- no-import-assign",
      "- no-new-native-nonconstructor",
      "- no-new-symbol",
      "- no-obj-calls",
      "- no-redeclare",
      "- no-setter-return",
      "- no-this-before-super",
      "- no-undef",
      "- no-unreachable",
      "- no-unsafe-negation",
      "no-var",
      "- no-with",
      "prefer-const",
      "prefer-rest-params",
      "prefer-spread",
      "@typescript-eslint/ban-ts-comment",
      "- no-array-constructor",
      "@typescript-eslint/no-array-constructor",
      "@typescript-eslint/no-duplicate-enum-values",
      "@typescript-eslint/no-empty-object-type",
      "@typescript-eslint/no-explicit-any",
      "@typescript-eslint/no-extra-non-null-assertion",
      "@typescript-eslint/no-misused-new",
      "@typescript-eslint/no-namespace",
      "@typescript-eslint/no-non-null-asserted-optional-chain",
      "@typescript-eslint/no-require-imports",
      "@typescript-eslint/no-this-alias",
      "@typescript-eslint/no-unnecessary-type-constraint",
      "@typescript-eslint/no-unsafe-declaration-merging",
      "@typescript-eslint/no-unsafe-function-type",
      "- no-unused-expressions",
      "@typescript-eslint/no-unused-expressions",
      "- no-unused-vars",
      "@typescript-eslint/no-unused-vars",
      "@typescript-eslint/no-wrapper-object-types",
      "@typescript-eslint/prefer-as-const",
      "@typescript-eslint/prefer-namespace-keyword",
      "@typescript-eslint/triple-slash-reference",
      "- class-methods-use-this",
      "- consistent-return",
      "- no-extra-boolean-cast",
      "- no-implied-eval",
      "- no-invalid-this",
      "- no-loop-func",
      "- no-loss-of-precision",
      "- no-use-before-define",
      "- no-useless-constructor",
      "@typescript-eslint/no-dynamic-delete",
      "@typescript-eslint/no-extraneous-class",
      "@typescript-eslint/no-invalid-void-type",
      "@typescript-eslint/no-non-null-asserted-nullish-coalescing",
      "@typescript-eslint/no-non-null-assertion",
      "@typescript-eslint/no-useless-constructor",
      "@typescript-eslint/prefer-literal-enum-member",
      "@typescript-eslint/unified-signatures",
      "@moso/no-force-cast-via-top-type",
      "@typescript-eslint/consistent-type-definitions",
      "@typescript-eslint/adjacent-overload-signatures",
      "@typescript-eslint/array-type",
      "@typescript-eslint/ban-tslint-comment",
      "@typescript-eslint/class-literal-property-style",
      "@typescript-eslint/consistent-generic-constructors",
      "@typescript-eslint/consistent-indexed-object-style",
      "@typescript-eslint/consistent-type-assertions",
      "@typescript-eslint/no-confusing-non-null-assertion",
      "- no-empty-function",
      "@typescript-eslint/no-empty-function",
      "@typescript-eslint/no-inferrable-types",
      "@typescript-eslint/prefer-for-of",
      "@typescript-eslint/prefer-function-type",
      "@stylistic/type-annotation-spacing",
      "@typescript-eslint/class-methods-use-this",
      "@typescript-eslint/consistent-type-imports",
      "@typescript-eslint/explicit-function-return-type",
      "- @typescript-eslint/explicit-member-accessibility",
      "@typescript-eslint/method-signature-style",
      "- @typescript-eslint/no-dupe-class-members",
      "@typescript-eslint/no-import-type-side-effects",
      "- @typescript-eslint/no-invalid-this",
      "@typescript-eslint/no-loop-func",
      "@typescript-eslint/no-use-before-define",
      "- @typescript-eslint/parameter-properties",
      "functional/no-mixed-types",
      "functional/prefer-property-signatures",
      "functional/readonly-type",
      "functional/type-declaration-immutability",
      "@typescript-eslint/naming-convention",
    ],
  },
  {
    "name": "moso/typescript/erasable-syntax",
    "plugins": [
      "erasable-syntax-only",
    ],
    "rules": [
      "erasable-syntax-only/enums",
      "erasable-syntax-only/import-aliases",
      "erasable-syntax-only/namespaces",
      "erasable-syntax-only/parameter-properties",
    ],
  },
  {
    "files": [
      "**/?(.)*.d.?([cm])ts",
    ],
    "name": "moso/typescript/dts-overrides",
    "rules": [
      "- @eslint-community/eslint-comments/no-unlimited-disable",
      "- @stylistic/quote-props",
      "- no-duplicate-imports",
      "- no-restricted-syntax",
      "- unused-imports/no-unused-vars",
    ],
  },
  {
    "files": [
      [
        "**/__tests__/**/?(.)*.?([cm])[jt]s?(x)",
        "**/?(.)*.spec.?([cm])[jt]s?(x)",
        "**/?(.)*.test.?([cm])[jt]s?(x)",
        "**/?(.)*.bench.?([cm])[jt]s?(x)",
        "**/?(.)*.benchmark.?([cm])[jt]s?(x)",
      ],
    ],
    "name": "moso/typescript/test-overrides",
    "rules": [
      "- @typescript-eslint/consistent-type-definitions",
      "- @typescript-eslint/no-unused-expressions",
      "- @typescript-eslint/triple-slash-reference",
      "- no-unused-expressions",
    ],
  },
  {
    "files": [
      "**/*.?([cm])js",
      "**/*.?([cm])jsx",
    ],
    "name": "moso/typescript/javascript-overrides",
    "rules": [
      "- @typescript-eslint/ban-ts-comment",
      "- @typescript-eslint/no-require-imports",
    ],
  },
  {
    "name": "moso/yaml/setup",
    "plugins": [
      "yml",
    ],
  },
  {
    "files": [
      "**/*.y?(a)ml",
    ],
    "language": "yml/yaml",
    "languageOptions": {
      "parser": "yaml-eslint-parser",
    },
    "name": "moso/yaml/rules",
    "rules": [
      "- @stylistic/spaced-comment",
      "yml/block-mapping",
      "yml/block-sequence",
      "yml/no-empty-key",
      "yml/no-empty-sequence-entry",
      "yml/no-irregular-whitespace",
      "yml/plain-scalar",
      "yml/vue-custom-block/no-parsing-error",
      "yml/block-mapping-question-indicator-newline",
      "yml/block-sequence-hyphen-indicator-newline",
      "yml/flow-mapping-curly-newline",
      "yml/flow-mapping-curly-spacing",
      "yml/flow-sequence-bracket-newline",
      "yml/flow-sequence-bracket-spacing",
      "yml/indent",
      "yml/key-spacing",
      "yml/no-tab-indent",
      "yml/spaced-comment",
      "yml/quotes",
    ],
  },
  {
    "files": [
      "**/bin/**/*",
      "**/bin.?([cm])[jt]s?(x)",
    ],
    "name": "moso/disables/bin",
    "rules": [
      "- @moso/no-import-from-dist",
      "- @moso/no-import-node-modules-by-path",
    ],
  },
  {
    "files": [
      "**/*.js",
      "**/*.cjs",
    ],
    "name": "moso/disables/cjs",
    "rules": [
      "- @typescript-eslint/no-require-imports",
    ],
  },
  {
    "files": [
      "**/cli/**/*.?([cm])[jt]s?(x)",
      "**/cli.?([cm])[jt]s?(x)",
    ],
    "name": "moso/disables/cli",
    "rules": [
      "- @moso/no-top-level-await",
      "- no-console",
    ],
  },
  {
    "files": [
      "**/*.config.?([cm])[jt]s?(x)",
      "**/*.config.*.?([cm])[jt]s?(x)",
    ],
    "name": "moso/disables/config-files",
    "rules": [
      "- @moso/no-top-level-await",
      "- @typescript-eslint/explicit-function-return-type",
      "- no-console",
    ],
  },
  {
    "files": [
      "**/*.d.?([cm])ts",
    ],
    "name": "moso/disables/dts",
    "rules": [
      "- @eslint-community/eslint-comments/no-unlimited-disable",
      "- import-lite/no-duplicates",
      "- unused-imports/no-unused-vars",
      "- no-restricted-syntax",
    ],
  },
  {
    "files": [
      "**/scripts/**/*.?([cm])[jt]s?(x)",
    ],
    "name": "moso/disables/scripts",
    "rules": [
      "- @moso/no-top-level-await",
      "- @typescript-eslint/explicit-function-return-type",
      "- functional/no-conditional-statements",
      "- functional/no-expression-statements",
      "- functional/no-loop-statements",
      "- functional/no-return-void",
      "- functional/no-throw-statements",
      "- node/no-sync",
      "- node/no-unpublished-import",
      "- no-console",
    ],
  },
  {
    "files": [
      "typings/**/?(.)*.?([cm])ts",
    ],
    "name": "moso/disables/typings",
    "rules": [
      "- functional/functional-parameters",
      "- functional/immutable-data",
      "- functional/no-classes",
      "- functional/no-class-inheritance",
      "- functional/no-conditional-statements",
      "- functional/no-expression-statements",
      "- functional/no-let",
      "- functional/no-loop-statements",
      "- functional/no-mixed-types",
      "- functional/no-promise-reject",
      "- functional/no-return-void",
      "- functional/no-this-expressions",
      "- functional/no-throw-statements",
      "- functional/no-try-statements",
      "- functional/prefer-immutable-types",
      "- functional/prefer-property-signatures",
      "- functional/prefer-readonly-type",
      "- functional/prefer-tacit",
      "- functional/readonly-type",
      "- functional/type-declaration-immutability",
      "- jsdoc/check-examples",
      "- jsdoc/check-indentation",
      "- jsdoc/check-line-alignment",
      "- jsdoc/check-param-names",
      "- jsdoc/check-property-names",
      "- jsdoc/check-types",
      "- jsdoc/check-values",
      "- jsdoc/no-bad-blocks",
      "- jsdoc/no-defaults",
      "- jsdoc/require-asterisk-prefix",
      "- jsdoc/require-description",
      "- jsdoc/require-description-complete-sentence",
      "- jsdoc/require-hyphen-before-param-description",
      "- jsdoc/require-jsdoc",
      "- jsdoc/require-param-name",
      "- jsdoc/require-param",
      "- jsdoc/require-property-name",
      "- jsdoc/require-property",
      "- jsdoc/require-returns-check",
      "- jsdoc/require-returns",
      "- jsdoc/require-throws",
      "- jsdoc/require-yields-check",
      "- jsdoc/tag-lines",
      "- jsdoc/check-access",
      "- jsdoc/empty-tags",
      "- jsdoc/implements-on-classes",
      "- jsdoc/no-multi-asterisks",
      "- jsdoc/require-property-description",
      "- jsdoc/require-returns-description",
      "- jsdoc/check-alignment",
      "- jsdoc/multiline-blocks",
      "- @typescript-eslint/consistent-type-definitions",
      "- @typescript-eslint/no-empty-object-type",
      "- @typescript-eslint/no-explicit-any",
      "- @typescript-eslint/no-unused-vars",
    ],
  },
]