[
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
      "**/*.astro",
      "**/*.vue",
    ],
    "name": "moso/eslint-comments",
    "plugins": [
      "@eslint-community/eslint-comments",
    ],
    "rules": [
      "@eslint-community/eslint-comments/disable-enable-pair",
      "@eslint-community/eslint-comments/no-aggregating-enable",
      "@eslint-community/eslint-comments/no-duplicate-disable",
      "@eslint-community/eslint-comments/no-unlimited-disable",
      "@eslint-community/eslint-comments/no-unused-enable",
    ],
  },
  {
    "ignores": [
      "**/node_modules",
      "**/dist",
      "**/lib",
      "**/package-lock.json",
      "**/yarn.lock",
      "**/pnpm-lock.yaml",
      "**/bun.lockb",
      "**/bun.lock",
      "**/output",
      "**/coverage",
      "**/temp",
      "**/.temp",
      "**/tmp",
      "**/.tmp",
      "**/.history",
      "**/.vitepress/cache",
      "**/.nuxt",
      "**/.next",
      "**/.vercel",
      "**/.changeset",
      "**/.idea",
      "**/.cache",
      "**/.output",
      "**/.vite-inspect",
      "**/.yarn",
      "**/vite.config.*.timestamp-*",
      "**/CHANGELOG*.md",
      "**/*.min.*",
      "**/LICENSE*",
      "**/__snapshots__",
      "**/auto-import?(s).ts",
      "**/auto-import?(s).d.ts",
      "**/components.ts",
      "**/components.d.ts",
      "**/typegen.ts",
      "**/typegen.d.ts",
    ],
    "name": "moso/ignores/globals",
  },
  {
    "name": "moso/imports",
    "plugins": [
      "@moso",
      "import-lite",
    ],
    "rules": [
      "@moso/no-import-duplicates",
      "@moso/no-import-from-dist",
      "@moso/no-import-node-modules-by-path",
      "import-lite/consistent-type-specifier-style",
      "import-lite/first",
      "import-lite/no-duplicates",
      "import-lite/no-mutable-exports",
      "import-lite/no-named-default",
      "import-lite/newline-after-import",
    ],
  },
  {
    "files": [
      "**/?(.)*.d.?([cm])ts",
      "**/*.?([cm])ts",
      "**/*.?([cm])tsx",
    ],
    "name": "moso/imports/typescript",
    "rules": [
      "@typescript-eslint/no-import-type-side-effects",
      "@typescript-eslint/consistent-type-imports",
    ],
  },
  {
    "languageOptions": {
      "ecmaVersion": "latest",
      "parserOptions": {
        "ecmaFeatures": {
          "jsx": true,
        },
        "ecmaVersion": "latest",
        "sourceType": "module",
      },
      "sourceType": "module",
    },
    "linterOptions": {
      "reportUnusedDisableDirectives": true,
    },
    "name": "moso/javascript",
    "plugins": [
      "@eslint/js",
      "unused-imports",
    ],
    "rules": [
      "constructor-super",
      "for-direction",
      "getter-return",
      "no-async-promise-executor",
      "no-case-declarations",
      "no-class-assign",
      "no-compare-neg-zero",
      "no-cond-assign",
      "no-const-assign",
      "no-constant-binary-expression",
      "no-constant-condition",
      "no-control-regex",
      "no-debugger",
      "no-delete-var",
      "no-dupe-args",
      "no-dupe-class-members",
      "no-dupe-else-if",
      "no-dupe-keys",
      "no-duplicate-case",
      "no-empty",
      "no-empty-character-class",
      "no-empty-pattern",
      "no-empty-static-block",
      "no-ex-assign",
      "no-extra-boolean-cast",
      "no-fallthrough",
      "no-func-assign",
      "no-global-assign",
      "no-import-assign",
      "no-invalid-regexp",
      "no-irregular-whitespace",
      "no-loss-of-precision",
      "no-misleading-character-class",
      "no-new-native-nonconstructor",
      "no-nonoctal-decimal-escape",
      "no-obj-calls",
      "no-octal",
      "no-prototype-builtins",
      "no-redeclare",
      "no-regex-spaces",
      "no-self-assign",
      "no-setter-return",
      "no-shadow-restricted-names",
      "no-sparse-arrays",
      "no-this-before-super",
      "no-unassigned-vars",
      "no-undef",
      "no-unexpected-multiline",
      "no-unreachable",
      "no-unsafe-finally",
      "no-unsafe-negation",
      "no-unsafe-optional-chaining",
      "no-unused-labels",
      "no-unused-private-class-members",
      "no-unused-vars",
      "no-useless-assignment",
      "no-useless-backreference",
      "no-useless-catch",
      "no-useless-escape",
      "no-with",
      "preserve-caught-error",
      "require-yield",
      "use-isnan",
      "valid-typeof",
      "array-callback-return",
      "no-await-in-loop",
      "no-constructor-return",
      "no-duplicate-imports",
      "no-inner-declarations",
      "no-promise-executor-return",
      "no-self-compare",
      "no-template-curly-in-string",
      "no-unmodified-loop-condition",
      "no-unreachable-loop",
      "no-use-before-define",
      "require-atomic-updates",
      "accessor-pairs",
      "arrow-body-style",
      "block-scoped-var",
      "- camelcase",
      "class-methods-use-this",
      "consistent-return",
      "- consistent-this",
      "curly",
      "default-case-last",
      "dot-notation",
      "eqeqeq",
      "func-name-matching",
      "func-style",
      "grouped-accessor-pairs",
      "guard-for-in",
      "new-cap",
      "no-alert",
      "no-array-constructor",
      "no-caller",
      "no-console",
      "no-else-return",
      "no-eq-null",
      "no-eval",
      "no-extra-bind",
      "no-implied-eval",
      "no-invalid-this",
      "no-iterator",
      "no-label-var",
      "no-labels",
      "no-lone-blocks",
      "no-lonely-if",
      "no-loop-func",
      "no-multi-assign",
      "no-multi-str",
      "no-new",
      "no-new-func",
      "no-new-wrappers",
      "no-object-constructor",
      "no-octal-escape",
      "no-param-reassign",
      "no-proto",
      "no-restricted-globals",
      "no-restricted-properties",
      "no-restricted-syntax",
      "- no-return-assign",
      "no-sequences",
      "no-throw-literal",
      "no-undef-init",
      "no-unneeded-ternary",
      "no-unused-expressions",
      "no-useless-call",
      "no-useless-computed-key",
      "no-useless-concat",
      "no-useless-constructor",
      "no-useless-rename",
      "no-var",
      "object-shorthand",
      "one-var",
      "operator-assignment",
      "prefer-arrow-callback",
      "prefer-const",
      "prefer-destructuring",
      "prefer-exponentiation-operator",
      "prefer-numeric-literals",
      "prefer-object-has-own",
      "prefer-object-spread",
      "prefer-promise-reject-errors",
      "prefer-regex-literals",
      "prefer-rest-params",
      "prefer-spread",
      "prefer-template",
      "radix",
      "require-await",
      "require-unicode-regexp",
      "strict",
      "symbol-description",
      "vars-on-top",
      "yoda",
      "unicode-bom",
      "unused-imports/no-unused-imports",
      "unused-imports/no-unused-vars",
      "max-classes-per-file",
      "sort-imports",
    ],
  },
  {
    "languageOptions": {},
    "name": "moso/node",
    "plugins": [
      "node",
    ],
    "rules": [
      "node/no-deprecated-api",
      "node/no-exports-assign",
      "node/no-extraneous-import",
      "node/no-extraneous-require",
      "node/no-missing-import",
      "node/no-missing-require",
      "node/no-process-exit",
      "node/no-unpublished-import",
      "node/no-unpublished-require",
      "node/no-unsupported-features/es-builtins",
      "node/no-unsupported-features/es-syntax",
      "node/no-unsupported-features/node-builtins",
      "node/process-exit-as-throw",
      "node/hashbang",
      "node/prefer-global/process",
      "node/prefer-global/text-decoder",
      "node/prefer-global/text-encoder",
      "node/prefer-global/url-search-params",
    ],
    "settings": {
      "node": {
        "version": "^22.22.2 || >=24",
      },
    },
  },
  {
    "files": [
      "**/?(.)*.d.?([cm])ts",
      "**/*.mjs",
      "**/*.?([cm])ts",
      "**/*.?([cm])tsx",
    ],
    "rules": [
      "- node/no-unsupported-features/es-syntax",
    ],
  },
  {
    "files": [
      "**/?(.)*.d.?([cm])ts",
      "**/*.?([cm])ts",
      "**/*.?([cm])tsx",
    ],
    "rules": [
      "- node/no-extraneous-import",
      "- node/no-missing-import",
      "- node/no-restricted-import",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
      "**/*.astro",
      "**/*.vue",
    ],
    "name": "moso/promise",
    "plugins": [
      "promise",
    ],
    "rules": [
      "promise/no-callback-in-promise",
      "promise/no-nesting",
      "promise/no-new-statics",
      "promise/no-promise-in-callback",
      "promise/no-return-in-finally",
      "promise/no-return-wrap",
      "promise/param-names",
      "promise/valid-params",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
      "**/*.astro",
      "**/*.vue",
    ],
    "name": "moso/regexp",
    "plugins": [
      "regexp",
    ],
    "rules": [
      "- no-empty-character-class",
      "- no-invalid-regexp",
      "- no-useless-backreference",
      "no-control-regex",
      "no-misleading-character-class",
      "no-regex-spaces",
      "prefer-regex-literals",
      "regexp/confusing-quantifier",
      "regexp/control-character-escape",
      "regexp/match-any",
      "regexp/negation",
      "regexp/no-contradiction-with-assertion",
      "regexp/no-dupe-characters-character-class",
      "regexp/no-dupe-disjunctions",
      "regexp/no-empty-alternative",
      "regexp/no-empty-capturing-group",
      "regexp/no-empty-character-class",
      "regexp/no-empty-group",
      "regexp/no-empty-lookarounds-assertion",
      "regexp/no-empty-string-literal",
      "regexp/no-escape-backspace",
      "regexp/no-extra-lookaround-assertions",
      "regexp/no-invalid-regexp",
      "regexp/no-invisible-character",
      "regexp/no-lazy-ends",
      "regexp/no-legacy-features",
      "regexp/no-misleading-capturing-group",
      "regexp/no-misleading-unicode-character",
      "regexp/no-missing-g-flag",
      "regexp/no-non-standard-flag",
      "regexp/no-obscure-range",
      "regexp/no-optional-assertion",
      "regexp/no-potentially-useless-backreference",
      "regexp/no-super-linear-backtracking",
      "regexp/no-trivially-nested-assertion",
      "regexp/no-trivially-nested-quantifier",
      "regexp/no-unused-capturing-group",
      "regexp/no-useless-assertions",
      "regexp/no-useless-backreference",
      "regexp/no-useless-character-class",
      "regexp/no-useless-dollar-replacements",
      "regexp/no-useless-escape",
      "regexp/no-useless-flag",
      "regexp/no-useless-lazy",
      "regexp/no-useless-non-capturing-group",
      "regexp/no-useless-quantifier",
      "regexp/no-useless-range",
      "regexp/no-useless-set-operand",
      "regexp/no-useless-string-literal",
      "regexp/no-useless-two-nums-quantifier",
      "regexp/no-zero-quantifier",
      "regexp/optimal-lookaround-quantifier",
      "regexp/optimal-quantifier-concatenation",
      "regexp/prefer-character-class",
      "regexp/prefer-d",
      "regexp/prefer-plus-quantifier",
      "regexp/prefer-predefined-assertion",
      "regexp/prefer-question-quantifier",
      "regexp/prefer-range",
      "regexp/prefer-set-operation",
      "regexp/prefer-star-quantifier",
      "regexp/prefer-unicode-codepoint-escapes",
      "regexp/prefer-w",
      "regexp/simplify-set-operations",
      "regexp/sort-flags",
      "- regexp/strict",
      "regexp/use-ignore-case",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
      "**/*.astro",
      "**/*.vue",
    ],
    "name": "moso/unicorn",
    "plugins": [
      "unicorn",
    ],
    "rules": [
      "- no-negated-condition",
      "- no-process-exit",
      "unicorn/better-dom-traversing",
      "- unicorn/catch-error-name",
      "- unicorn/class-reference-in-static-methods",
      "- unicorn/comment-content",
      "- unicorn/consistent-assert",
      "- unicorn/consistent-boolean-name",
      "- unicorn/consistent-class-member-order",
      "unicorn/consistent-compound-words",
      "- unicorn/consistent-conditional-object-spread",
      "unicorn/consistent-date-clone",
      "- unicorn/consistent-destructuring",
      "- unicorn/consistent-empty-array-spread",
      "unicorn/consistent-existence-index-check",
      "unicorn/consistent-export-decorator-position",
      "- unicorn/consistent-function-scoping",
      "- unicorn/consistent-function-style",
      "- unicorn/consistent-json-file-read",
      "unicorn/consistent-optional-chaining",
      "- unicorn/consistent-template-literal-escape",
      "- unicorn/consistent-tuple-labels",
      "- unicorn/custom-error-definition",
      "- unicorn/default-export-style",
      "unicorn/dom-node-dataset",
      "- unicorn/empty-brace-spaces",
      "unicorn/error-message",
      "unicorn/escape-case",
      "unicorn/expiring-todo-comments",
      "- unicorn/explicit-length-check",
      "unicorn/explicit-timer-delay",
      "- unicorn/filename-case",
      "- unicorn/id-match",
      "unicorn/import-style",
      "- unicorn/isolated-functions",
      "- unicorn/logical-assignment-operators",
      "- unicorn/max-nested-calls",
      "- unicorn/name-replacements",
      "unicorn/new-for-builtins",
      "unicorn/no-abusive-eslint-disable",
      "unicorn/no-accessor-recursion",
      "unicorn/no-accidental-bitwise-operator",
      "unicorn/no-anonymous-default-export",
      "- unicorn/no-array-callback-reference",
      "- unicorn/no-array-concat-in-loop",
      "unicorn/no-array-fill-with-reference-type",
      "unicorn/no-array-from-fill",
      "- unicorn/no-array-front-mutation",
      "unicorn/no-array-method-this-argument",
      "- unicorn/no-array-reduce",
      "unicorn/no-array-reverse",
      "unicorn/no-array-sort",
      "unicorn/no-array-sort-for-min-max",
      "- unicorn/no-array-splice",
      "- unicorn/no-asterisk-prefix-in-documentation-comments",
      "unicorn/no-async-promise-finally",
      "- unicorn/no-await-expression-member",
      "unicorn/no-await-in-promise-methods",
      "unicorn/no-blob-to-file",
      "unicorn/no-boolean-sort-comparator",
      "- unicorn/no-break-in-nested-loop",
      "unicorn/no-canvas-to-image",
      "unicorn/no-chained-comparison",
      "unicorn/no-collection-bracket-access",
      "- unicorn/no-computed-property-existence-check",
      "- unicorn/no-confusing-array-splice",
      "- unicorn/no-confusing-array-with",
      "unicorn/no-console-spaces",
      "unicorn/no-constant-zero-expression",
      "unicorn/no-declarations-before-early-exit",
      "unicorn/no-document-cookie",
      "unicorn/no-double-comparison",
      "- unicorn/no-duplicate-if-branches",
      "unicorn/no-duplicate-logical-operands",
      "- unicorn/no-duplicate-loops",
      "- unicorn/no-duplicate-set-values",
      "unicorn/no-empty-file",
      "unicorn/no-error-property-assignment",
      "unicorn/no-exports-in-scripts",
      "unicorn/no-for-each",
      "- unicorn/no-for-loop",
      "unicorn/no-global-object-property-assignment",
      "- unicorn/no-immediate-mutation",
      "unicorn/no-impossible-length-comparison",
      "- unicorn/no-incorrect-query-selector",
      "- unicorn/no-incorrect-template-string-interpolation",
      "unicorn/no-instanceof-builtins",
      "unicorn/no-invalid-argument-count",
      "unicorn/no-invalid-character-comparison",
      "unicorn/no-invalid-fetch-options",
      "- unicorn/no-invalid-file-input-accept",
      "unicorn/no-invalid-remove-event-listener",
      "unicorn/no-invalid-well-known-symbol-methods",
      "- unicorn/no-keyword-prefix",
      "- unicorn/no-late-current-target-access",
      "- unicorn/no-late-event-control",
      "unicorn/no-lonely-if",
      "- unicorn/no-loop-iterable-mutation",
      "unicorn/no-magic-array-flat-depth",
      "- unicorn/no-manually-wrapped-comments",
      "- unicorn/no-mismatched-map-key",
      "unicorn/no-misrefactored-assignment",
      "unicorn/no-named-default",
      "unicorn/no-negated-array-predicate",
      "unicorn/no-negated-comparison",
      "unicorn/no-negated-condition",
      "unicorn/no-negation-in-equality-check",
      "- unicorn/no-nested-ternary",
      "unicorn/no-new-array",
      "unicorn/no-new-buffer",
      "- unicorn/no-non-function-verb-prefix",
      "unicorn/no-nonstandard-builtin-properties",
      "- unicorn/no-null",
      "unicorn/no-object-as-default-parameter",
      "- unicorn/no-object-methods-with-collections",
      "- unicorn/no-optional-chaining-on-undeclared-variable",
      "unicorn/no-process-exit",
      "unicorn/no-redundant-comparison",
      "- unicorn/no-return-array-push",
      "- unicorn/no-selector-as-dom-name",
      "unicorn/no-single-promise-in-promise-methods",
      "unicorn/no-static-only-class",
      "unicorn/no-subtraction-comparison",
      "unicorn/no-thenable",
      "unicorn/no-this-assignment",
      "- unicorn/no-this-outside-of-class",
      "- unicorn/no-top-level-assignment-in-function",
      "unicorn/no-top-level-side-effects",
      "unicorn/no-typeof-undefined",
      "- unicorn/no-uncalled-method",
      "- unicorn/no-undeclared-class-members",
      "unicorn/no-unnecessary-array-flat-depth",
      "- unicorn/no-unnecessary-array-flat-map",
      "unicorn/no-unnecessary-array-splice-count",
      "unicorn/no-unnecessary-await",
      "- unicorn/no-unnecessary-boolean-comparison",
      "unicorn/no-unnecessary-fetch-options",
      "unicorn/no-unnecessary-global-this",
      "unicorn/no-unnecessary-nested-ternary",
      "unicorn/no-unnecessary-polyfills",
      "unicorn/no-unnecessary-slice-end",
      "- unicorn/no-unnecessary-splice",
      "unicorn/no-unreadable-array-destructuring",
      "- unicorn/no-unreadable-for-of-expression",
      "unicorn/no-unreadable-iife",
      "- unicorn/no-unreadable-new-expression",
      "unicorn/no-unreadable-object-destructuring",
      "unicorn/no-unsafe-buffer-conversion",
      "- unicorn/no-unsafe-dom-html",
      "unicorn/no-unsafe-promise-all-settled-values",
      "- unicorn/no-unsafe-property-key",
      "- unicorn/no-unsafe-string-replacement",
      "unicorn/no-unused-array-method-return",
      "- unicorn/no-unused-properties",
      "unicorn/no-useless-boolean-cast",
      "unicorn/no-useless-coercion",
      "unicorn/no-useless-collection-argument",
      "unicorn/no-useless-compound-assignment",
      "unicorn/no-useless-concat",
      "unicorn/no-useless-continue",
      "unicorn/no-useless-delete-check",
      "- unicorn/no-useless-else",
      "unicorn/no-useless-error-capture-stack-trace",
      "unicorn/no-useless-fallback-in-spread",
      "unicorn/no-useless-iterator-to-array",
      "unicorn/no-useless-length-check",
      "unicorn/no-useless-logical-operand",
      "unicorn/no-useless-override",
      "unicorn/no-useless-promise-resolve-reject",
      "- unicorn/no-useless-recursion",
      "unicorn/no-useless-spread",
      "unicorn/no-useless-switch-case",
      "unicorn/no-useless-template-literals",
      "unicorn/no-useless-undefined",
      "unicorn/no-xor-as-exponentiation",
      "unicorn/no-zero-fractions",
      "unicorn/number-literal-case",
      "unicorn/numeric-separators-style",
      "- unicorn/operator-assignment",
      "- unicorn/prefer-abort-signal-any",
      "- unicorn/prefer-abort-signal-timeout",
      "unicorn/prefer-add-event-listener",
      "unicorn/prefer-add-event-listener-options",
      "unicorn/prefer-aggregate-error",
      "unicorn/prefer-array-find",
      "unicorn/prefer-array-flat",
      "unicorn/prefer-array-flat-map",
      "- unicorn/prefer-array-from-async",
      "unicorn/prefer-array-from-map",
      "unicorn/prefer-array-from-range",
      "unicorn/prefer-array-index-of",
      "- unicorn/prefer-array-iterable-methods",
      "unicorn/prefer-array-last-methods",
      "- unicorn/prefer-array-slice",
      "unicorn/prefer-array-some",
      "unicorn/prefer-at",
      "unicorn/prefer-await",
      "unicorn/prefer-bigint-literals",
      "unicorn/prefer-blob-reading-methods",
      "unicorn/prefer-block-statement-over-iife",
      "unicorn/prefer-boolean-return",
      "unicorn/prefer-class-fields",
      "unicorn/prefer-classlist-toggle",
      "unicorn/prefer-code-point",
      "- unicorn/prefer-continue",
      "unicorn/prefer-date-now",
      "unicorn/prefer-default-parameters",
      "unicorn/prefer-direct-iteration",
      "- unicorn/prefer-dispose",
      "unicorn/prefer-dom-node-append",
      "- unicorn/prefer-dom-node-html-methods",
      "unicorn/prefer-dom-node-remove",
      "unicorn/prefer-dom-node-replace-children",
      "unicorn/prefer-dom-node-text-content",
      "unicorn/prefer-early-return",
      "- unicorn/prefer-else-if",
      "- unicorn/prefer-error-is-error",
      "unicorn/prefer-event-target",
      "- unicorn/prefer-export-from",
      "unicorn/prefer-flat-math-min-max",
      "- unicorn/prefer-get-or-insert-computed",
      "unicorn/prefer-global-number-constants",
      "unicorn/prefer-global-this",
      "- unicorn/prefer-group-by",
      "unicorn/prefer-has-check",
      "- unicorn/prefer-hoisting-branch-code",
      "- unicorn/prefer-https",
      "unicorn/prefer-identifier-import-export-specifiers",
      "- unicorn/prefer-import-meta-properties",
      "unicorn/prefer-includes",
      "- unicorn/prefer-includes-over-repeated-comparisons",
      "unicorn/prefer-iterable-in-constructor",
      "- unicorn/prefer-iterator-concat",
      "unicorn/prefer-iterator-helpers",
      "- unicorn/prefer-iterator-to-array",
      "unicorn/prefer-iterator-to-array-at-end",
      "unicorn/prefer-keyboard-event-key",
      "- unicorn/prefer-location-assign",
      "unicorn/prefer-logical-operator-over-ternary",
      "unicorn/prefer-map-from-entries",
      "unicorn/prefer-math-abs",
      "unicorn/prefer-math-constants",
      "unicorn/prefer-math-min-max",
      "unicorn/prefer-math-trunc",
      "unicorn/prefer-minimal-ternary",
      "unicorn/prefer-modern-dom-apis",
      "unicorn/prefer-modern-math-apis",
      "unicorn/prefer-module",
      "unicorn/prefer-native-coercion-functions",
      "unicorn/prefer-negative-index",
      "unicorn/prefer-node-protocol",
      "unicorn/prefer-number-coercion",
      "- unicorn/prefer-number-is-safe-integer",
      "unicorn/prefer-number-properties",
      "unicorn/prefer-object-define-properties",
      "- unicorn/prefer-object-destructuring-defaults",
      "unicorn/prefer-object-from-entries",
      "unicorn/prefer-object-iterable-methods",
      "- unicorn/prefer-observer-apis",
      "unicorn/prefer-optional-catch-binding",
      "unicorn/prefer-path2d",
      "- unicorn/prefer-private-class-fields",
      "- unicorn/prefer-promise-try",
      "unicorn/prefer-promise-with-resolvers",
      "unicorn/prefer-prototype-methods",
      "- unicorn/prefer-query-selector",
      "unicorn/prefer-queue-microtask",
      "unicorn/prefer-reflect-apply",
      "- unicorn/prefer-regexp-escape",
      "unicorn/prefer-regexp-test",
      "unicorn/prefer-response-static-json",
      "- unicorn/prefer-scoped-selector",
      "unicorn/prefer-set-has",
      "- unicorn/prefer-set-methods",
      "unicorn/prefer-set-size",
      "- unicorn/prefer-short-arrow-method",
      "unicorn/prefer-simple-condition-first",
      "unicorn/prefer-simple-sort-comparator",
      "unicorn/prefer-simplified-conditions",
      "unicorn/prefer-single-array-predicate",
      "unicorn/prefer-single-call",
      "- unicorn/prefer-single-object-destructuring",
      "unicorn/prefer-single-replace",
      "- unicorn/prefer-smaller-scope",
      "unicorn/prefer-split-limit",
      "- unicorn/prefer-spread",
      "unicorn/prefer-string-match-all",
      "unicorn/prefer-string-pad-start-end",
      "unicorn/prefer-string-raw",
      "unicorn/prefer-string-repeat",
      "unicorn/prefer-string-replace-all",
      "unicorn/prefer-string-slice",
      "unicorn/prefer-string-starts-ends-with",
      "unicorn/prefer-string-trim-start-end",
      "unicorn/prefer-structured-clone",
      "unicorn/prefer-switch",
      "- unicorn/prefer-temporal",
      "unicorn/prefer-ternary",
      "unicorn/prefer-toggle-attribute",
      "unicorn/prefer-top-level-await",
      "unicorn/prefer-type-error",
      "- unicorn/prefer-type-literal-last",
      "- unicorn/prefer-uint8array-base64",
      "unicorn/prefer-unary-minus",
      "unicorn/prefer-unicode-code-point-escapes",
      "unicorn/prefer-url-can-parse",
      "unicorn/prefer-url-href",
      "unicorn/prefer-url-search-parameters",
      "unicorn/prefer-while-loop-condition",
      "unicorn/relative-url-style",
      "unicorn/require-array-join-separator",
      "unicorn/require-array-sort-compare",
      "unicorn/require-css-escape",
      "unicorn/require-module-attributes",
      "unicorn/require-module-specifiers",
      "unicorn/require-number-to-fixed-digits-argument",
      "unicorn/require-passive-events",
      "- unicorn/require-post-message-target-origin",
      "unicorn/require-proxy-trap-boolean-return",
      "- unicorn/string-content",
      "- unicorn/switch-case-braces",
      "- unicorn/switch-case-break-position",
      "- unicorn/template-indent",
      "unicorn/text-encoding-identifier-case",
      "unicorn/throw-new-error",
      "- unicorn/try-complexity",
    ],
  },
  {
    "files": [
      "**/*.?([cm])jsx",
      "**/*.?([cm])tsx",
    ],
    "languageOptions": {
      "parserOptions": {
        "ecmaFeatures": {
          "jsx": true,
        },
      },
    },
    "name": "moso/jsx/setup",
  },
  {
    "name": "moso/jsx/rules",
    "rules": [
      "@stylistic/jsx-curly-spacing",
      "- @stylistic/jsx-one-expression-per-line",
    ],
  },
  {
    "name": "moso/stylistic",
    "plugins": [
      "@stylistic",
    ],
    "rules": [
      "@stylistic/array-bracket-spacing",
      "@stylistic/arrow-parens",
      "@stylistic/arrow-spacing",
      "@stylistic/block-spacing",
      "@stylistic/brace-style",
      "@stylistic/comma-dangle",
      "@stylistic/comma-spacing",
      "@stylistic/comma-style",
      "@stylistic/computed-property-spacing",
      "@stylistic/dot-location",
      "@stylistic/eol-last",
      "@stylistic/generator-star-spacing",
      "@stylistic/indent",
      "@stylistic/indent-binary-ops",
      "@stylistic/key-spacing",
      "@stylistic/keyword-spacing",
      "@stylistic/lines-between-class-members",
      "@stylistic/max-statements-per-line",
      "@stylistic/member-delimiter-style",
      "@stylistic/multiline-ternary",
      "@stylistic/new-parens",
      "@stylistic/no-extra-parens",
      "@stylistic/no-floating-decimal",
      "@stylistic/no-mixed-operators",
      "@stylistic/no-mixed-spaces-and-tabs",
      "@stylistic/no-multi-spaces",
      "@stylistic/no-multiple-empty-lines",
      "@stylistic/no-tabs",
      "@stylistic/no-trailing-spaces",
      "@stylistic/no-whitespace-before-property",
      "@stylistic/object-curly-spacing",
      "@stylistic/operator-linebreak",
      "@stylistic/padded-blocks",
      "@stylistic/quote-props",
      "@stylistic/quotes",
      "@stylistic/rest-spread-spacing",
      "@stylistic/semi",
      "@stylistic/semi-spacing",
      "@stylistic/space-before-blocks",
      "@stylistic/space-before-function-paren",
      "@stylistic/space-in-parens",
      "@stylistic/space-infix-ops",
      "@stylistic/space-unary-ops",
      "@stylistic/spaced-comment",
      "@stylistic/template-curly-spacing",
      "@stylistic/template-tag-spacing",
      "@stylistic/type-annotation-spacing",
      "@stylistic/type-generic-spacing",
      "@stylistic/type-named-tuple-spacing",
      "@stylistic/wrap-iife",
      "@stylistic/yield-star-spacing",
      "@stylistic/jsx-closing-bracket-location",
      "@stylistic/jsx-closing-tag-location",
      "@stylistic/jsx-curly-brace-presence",
      "@stylistic/jsx-curly-newline",
      "@stylistic/jsx-curly-spacing",
      "@stylistic/jsx-equals-spacing",
      "@stylistic/jsx-first-prop-new-line",
      "@stylistic/jsx-function-call-newline",
      "@stylistic/jsx-indent-props",
      "@stylistic/jsx-max-props-per-line",
      "@stylistic/jsx-one-expression-per-line",
      "@stylistic/jsx-quotes",
      "@stylistic/jsx-tag-spacing",
      "@stylistic/jsx-wrap-multilines",
    ],
  },
  {
    "languageOptions": {},
    "name": "moso/test/setup",
    "plugins": [
      "no-only-tests",
      "vitest",
    ],
    "settings": {
      "vitest": {
        "typecheck": true,
      },
    },
  },
  {
    "files": [
      "**/__tests__/**/?(.)*.?([cm])[jt]s?(x)",
      "**/?(.)*.spec.?([cm])[jt]s?(x)",
      "**/?(.)*.test.?([cm])[jt]s?(x)",
      "**/?(.)*.bench.?([cm])[jt]s?(x)",
      "**/?(.)*.benchmark.?([cm])[jt]s?(x)",
    ],
    "name": "moso/test/rules",
    "rules": [
      "- functional/functional-parameters",
      "- functional/immutable-data",
      "- functional/no-classes",
      "- functional/no-class-inheritance",
      "- functional/no-conditional-statements",
      "- functional/no-expression-statements",
      "- functional/no-let",
      "- functional/no-loop-statements",
      "- functional/no-mixed-types",
      "- functional/no-promise-reject",
      "- functional/no-return-void",
      "- functional/no-this-expressions",
      "- functional/no-throw-statements",
      "- functional/no-try-statements",
      "- functional/prefer-immutable-types",
      "- functional/prefer-property-signatures",
      "- functional/prefer-readonly-type",
      "- functional/prefer-tacit",
      "- functional/readonly-type",
      "- functional/type-declaration-immutability",
      "- @moso/no-top-level-await",
      "- jsdoc/require-jsdoc",
      "- node/no-sync",
      "- node/prefer-global/process",
      "- regexp/no-super-linear-backtracking",
      "- unicorn/consistent-function-scoping",
      "- unicorn/prefer-module",
      "- @typescript-eslint/consistent-type-definitions",
      "- @typescript-eslint/no-unsafe-argument",
      "- @typescript-eslint/no-unsafe-assignment",
      "- @typescript-eslint/no-unsafe-call",
      "- @typescript-eslint/no-unsafe-member-access",
      "- @typescript-eslint/no-unsafe-return",
      "- @typescript-eslint/no-unused-expressions",
      "- @typescript-eslint/no-unused-vars",
      "- @typescript-eslint/strict-boolean-expressions",
      "no-only-tests/no-only-tests",
      "vitest/expect-expect",
      "vitest/no-commented-out-tests",
      "vitest/no-conditional-expect",
      "vitest/no-disabled-tests",
      "vitest/no-focused-tests",
      "vitest/no-identical-title",
      "vitest/no-import-node-test",
      "vitest/no-interpolation-in-snapshots",
      "vitest/no-mocks-import",
      "vitest/no-standalone-expect",
      "vitest/no-unneeded-async-expect-function",
      "vitest/prefer-called-exactly-once-with",
      "vitest/require-local-test-context-for-concurrent-snapshots",
      "vitest/valid-describe-callback",
      "- vitest/valid-expect",
      "vitest/valid-expect-in-promise",
      "- vitest/valid-title",
      "vitest/consistent-test-it",
      "vitest/prefer-hooks-in-order",
      "vitest/prefer-lowercase-title",
    ],
  },
  {
    "name": "moso/toml/setup",
    "plugins": [
      "toml",
    ],
  },
  {
    "files": [
      "**/*.toml",
    ],
    "languageOptions": {
      "parser": "toml-eslint-parser",
    },
    "name": "moso/toml/rules",
    "rules": [
      "- @stylistic/spaced-comment",
      "toml/comma-style",
      "toml/keys-order",
      "toml/no-space-dots",
      "toml/no-unreadable-number-separator",
      "toml/precision-of-fractional-seconds",
      "toml/precision-of-integer",
      "toml/tables-order",
      "toml/vue-custom-block/no-parsing-error",
      "toml/array-bracket-newline",
      "toml/array-bracket-spacing",
      "toml/array-element-newline",
      "toml/indent",
      "toml/inline-table-curly-spacing",
      "toml/key-spacing",
      "toml/padding-line-between-pairs",
      "toml/padding-line-between-tables",
      "toml/quoted-keys",
      "toml/spaced-comment",
      "toml/table-bracket-spacing",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
    ],
    "languageOptions": {
      "parser": "typescript-eslint/parser",
      "parserOptions": {
        "ecmaFeatures": {
          "jsx": true,
        },
        "ecmaVersion": "latest",
        "extraFileExtensions": [],
        "jsxPragma": undefined,
        "sourceType": "module",
        "warnOnUnsupportedTypeScriptVersion": true,
      },
    },
    "name": "moso/typescript/setup",
    "plugins": [
      "@typescript-eslint",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
    ],
    "name": "moso/typescript/rules",
    "rules": [
      "- constructor-super",
      "- getter-return",
      "- no-class-assign",
      "- no-const-assign",
      "- no-dupe-args",
      "- no-dupe-class-members",
      "- no-dupe-keys",
      "- no-func-assign",
      "- no-import-assign",
      "- no-new-native-nonconstructor",
      "- no-new-symbol",
      "- no-obj-calls",
      "- no-redeclare",
      "- no-setter-return",
      "- no-this-before-super",
      "- no-undef",
      "- no-unreachable",
      "- no-unsafe-negation",
      "no-var",
      "- no-with",
      "prefer-const",
      "prefer-rest-params",
      "prefer-spread",
      "@typescript-eslint/ban-ts-comment",
      "- no-array-constructor",
      "@typescript-eslint/no-array-constructor",
      "@typescript-eslint/no-duplicate-enum-values",
      "@typescript-eslint/no-empty-object-type",
      "@typescript-eslint/no-explicit-any",
      "@typescript-eslint/no-extra-non-null-assertion",
      "@typescript-eslint/no-misused-new",
      "@typescript-eslint/no-namespace",
      "@typescript-eslint/no-non-null-asserted-optional-chain",
      "@typescript-eslint/no-require-imports",
      "@typescript-eslint/no-this-alias",
      "@typescript-eslint/no-unnecessary-type-constraint",
      "@typescript-eslint/no-unsafe-declaration-merging",
      "@typescript-eslint/no-unsafe-function-type",
      "- no-unused-expressions",
      "@typescript-eslint/no-unused-expressions",
      "- no-unused-vars",
      "@typescript-eslint/no-unused-vars",
      "@typescript-eslint/no-wrapper-object-types",
      "@typescript-eslint/prefer-as-const",
      "@typescript-eslint/prefer-namespace-keyword",
      "- @typescript-eslint/triple-slash-reference",
      "- class-methods-use-this",
      "- consistent-return",
      "- no-extra-boolean-cast",
      "- no-implied-eval",
      "- no-invalid-this",
      "- no-loop-func",
      "- no-loss-of-precision",
      "- no-use-before-define",
      "- no-useless-constructor",
      "- @typescript-eslint/no-dynamic-delete",
      "- @typescript-eslint/no-invalid-void-type",
      "- @typescript-eslint/no-extraneous-class",
      "- @typescript-eslint/no-non-null-assertion",
      "- @typescript-eslint/unified-signatures",
      "@typescript-eslint/adjacent-overload-signatures",
      "@typescript-eslint/array-type",
      "@typescript-eslint/ban-tslint-comment",
      "@typescript-eslint/class-literal-property-style",
      "@typescript-eslint/consistent-generic-constructors",
      "@typescript-eslint/consistent-indexed-object-style",
      "@typescript-eslint/consistent-type-assertions",
      "@typescript-eslint/consistent-type-definitions",
      "@typescript-eslint/no-confusing-non-null-assertion",
      "- no-empty-function",
      "@typescript-eslint/no-empty-function",
      "@typescript-eslint/no-inferrable-types",
      "@typescript-eslint/prefer-for-of",
      "@typescript-eslint/prefer-function-type",
      "@stylistic/type-annotation-spacing",
      "@typescript-eslint/class-methods-use-this",
      "@typescript-eslint/consistent-type-imports",
      "@typescript-eslint/explicit-function-return-type",
      "- @typescript-eslint/explicit-member-accessibility",
      "@typescript-eslint/method-signature-style",
      "- @typescript-eslint/no-dupe-class-members",
      "@typescript-eslint/no-import-type-side-effects",
      "- @typescript-eslint/no-invalid-this",
      "@typescript-eslint/no-loop-func",
      "@typescript-eslint/no-use-before-define",
      "@typescript-eslint/no-useless-constructor",
      "- @typescript-eslint/parameter-properties",
    ],
  },
  {
    "files": [
      "**/?(.)*.d.?([cm])ts",
    ],
    "name": "moso/typescript/dts-overrides",
    "rules": [
      "- @eslint-community/eslint-comments/no-unlimited-disable",
      "- @stylistic/quote-props",
      "- no-duplicate-imports",
      "- no-restricted-syntax",
      "- unused-imports/no-unused-vars",
    ],
  },
  {
    "files": [
      [
        "**/__tests__/**/?(.)*.?([cm])[jt]s?(x)",
        "**/?(.)*.spec.?([cm])[jt]s?(x)",
        "**/?(.)*.test.?([cm])[jt]s?(x)",
        "**/?(.)*.bench.?([cm])[jt]s?(x)",
        "**/?(.)*.benchmark.?([cm])[jt]s?(x)",
      ],
    ],
    "name": "moso/typescript/test-overrides",
    "rules": [
      "- @typescript-eslint/consistent-type-definitions",
      "- @typescript-eslint/no-unused-expressions",
      "- @typescript-eslint/triple-slash-reference",
      "- no-unused-expressions",
    ],
  },
  {
    "files": [
      "**/*.?([cm])js",
      "**/*.?([cm])jsx",
    ],
    "name": "moso/typescript/javascript-overrides",
    "rules": [
      "- @typescript-eslint/ban-ts-comment",
      "- @typescript-eslint/no-require-imports",
    ],
  },
  {
    "name": "moso/yaml/setup",
    "plugins": [
      "yml",
    ],
  },
  {
    "files": [
      "**/*.y?(a)ml",
    ],
    "language": "yml/yaml",
    "languageOptions": {
      "parser": "yaml-eslint-parser",
    },
    "name": "moso/yaml/rules",
    "rules": [
      "- @stylistic/spaced-comment",
      "yml/block-mapping",
      "yml/block-sequence",
      "yml/no-empty-key",
      "yml/no-empty-sequence-entry",
      "yml/no-irregular-whitespace",
      "yml/plain-scalar",
      "yml/vue-custom-block/no-parsing-error",
      "yml/block-mapping-question-indicator-newline",
      "yml/block-sequence-hyphen-indicator-newline",
      "yml/flow-mapping-curly-newline",
      "yml/flow-mapping-curly-spacing",
      "yml/flow-sequence-bracket-newline",
      "yml/flow-sequence-bracket-spacing",
      "yml/indent",
      "yml/key-spacing",
      "yml/no-tab-indent",
      "yml/spaced-comment",
      "yml/quotes",
    ],
  },
  {
    "files": [
      "**/bin/**/*",
      "**/bin.?([cm])[jt]s?(x)",
    ],
    "name": "moso/disables/bin",
    "rules": [
      "- @moso/no-import-from-dist",
      "- @moso/no-import-node-modules-by-path",
    ],
  },
  {
    "files": [
      "**/*.js",
      "**/*.cjs",
    ],
    "name": "moso/disables/cjs",
    "rules": [
      "- @typescript-eslint/no-require-imports",
    ],
  },
  {
    "files": [
      "**/cli/**/*.?([cm])[jt]s?(x)",
      "**/cli.?([cm])[jt]s?(x)",
    ],
    "name": "moso/disables/cli",
    "rules": [
      "- @moso/no-top-level-await",
      "- no-console",
    ],
  },
  {
    "files": [
      "**/*.config.?([cm])[jt]s?(x)",
      "**/*.config.*.?([cm])[jt]s?(x)",
    ],
    "name": "moso/disables/config-files",
    "rules": [
      "- @moso/no-top-level-await",
      "- @typescript-eslint/explicit-function-return-type",
      "- no-console",
    ],
  },
  {
    "files": [
      "**/*.d.?([cm])ts",
    ],
    "name": "moso/disables/dts",
    "rules": [
      "- @eslint-community/eslint-comments/no-unlimited-disable",
      "- import-lite/no-duplicates",
      "- unused-imports/no-unused-vars",
      "- no-restricted-syntax",
    ],
  },
  {
    "files": [
      "**/scripts/**/*.?([cm])[jt]s?(x)",
    ],
    "name": "moso/disables/scripts",
    "rules": [
      "- @moso/no-top-level-await",
      "- @typescript-eslint/explicit-function-return-type",
      "- functional/no-conditional-statements",
      "- functional/no-expression-statements",
      "- functional/no-loop-statements",
      "- functional/no-return-void",
      "- functional/no-throw-statements",
      "- node/no-sync",
      "- node/no-unpublished-import",
      "- no-console",
    ],
  },
  {
    "files": [
      "typings/**/?(.)*.?([cm])ts",
    ],
    "name": "moso/disables/typings",
    "rules": [
      "- functional/functional-parameters",
      "- functional/immutable-data",
      "- functional/no-classes",
      "- functional/no-class-inheritance",
      "- functional/no-conditional-statements",
      "- functional/no-expression-statements",
      "- functional/no-let",
      "- functional/no-loop-statements",
      "- functional/no-mixed-types",
      "- functional/no-promise-reject",
      "- functional/no-return-void",
      "- functional/no-this-expressions",
      "- functional/no-throw-statements",
      "- functional/no-try-statements",
      "- functional/prefer-immutable-types",
      "- functional/prefer-property-signatures",
      "- functional/prefer-readonly-type",
      "- functional/prefer-tacit",
      "- functional/readonly-type",
      "- functional/type-declaration-immutability",
      "- jsdoc/check-examples",
      "- jsdoc/check-indentation",
      "- jsdoc/check-line-alignment",
      "- jsdoc/check-param-names",
      "- jsdoc/check-property-names",
      "- jsdoc/check-types",
      "- jsdoc/check-values",
      "- jsdoc/no-bad-blocks",
      "- jsdoc/no-defaults",
      "- jsdoc/require-asterisk-prefix",
      "- jsdoc/require-description",
      "- jsdoc/require-description-complete-sentence",
      "- jsdoc/require-hyphen-before-param-description",
      "- jsdoc/require-jsdoc",
      "- jsdoc/require-param-name",
      "- jsdoc/require-param",
      "- jsdoc/require-property-name",
      "- jsdoc/require-property",
      "- jsdoc/require-returns-check",
      "- jsdoc/require-returns",
      "- jsdoc/require-throws",
      "- jsdoc/require-yields-check",
      "- jsdoc/tag-lines",
      "- jsdoc/check-access",
      "- jsdoc/empty-tags",
      "- jsdoc/implements-on-classes",
      "- jsdoc/no-multi-asterisks",
      "- jsdoc/require-property-description",
      "- jsdoc/require-returns-description",
      "- jsdoc/check-alignment",
      "- jsdoc/multiline-blocks",
      "- @typescript-eslint/consistent-type-definitions",
      "- @typescript-eslint/no-empty-object-type",
      "- @typescript-eslint/no-explicit-any",
      "- @typescript-eslint/no-unused-vars",
    ],
  },
]