name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read

env:
  SKIP_INSTALL_SIMPLE_GIT_HOOKS: 1

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/prepare
      - run: bun run build
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/prepare
      - run: bun run lint
  typecheck:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/prepare
      - run: bun run typecheck
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/prepare
      - run: bun run test --coverage
      - env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        if: always()
        uses: codecov/codecov-action@v7
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [lts/*]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/prepare
        run: bun run test
